-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity knn_vote is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    knn_set_V_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    knn_set_V_ce0 : OUT STD_LOGIC;
    knn_set_V_q0 : IN STD_LOGIC_VECTOR (5 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (3 downto 0) );
end;


architecture behav of knn_vote is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal i_fu_246_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln169_fu_267_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln169_reg_592 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal i_2_fu_277_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal i_2_reg_600 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln169_fu_271_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sorted_labels_q0 : STD_LOGIC_VECTOR (3 downto 0);
    signal sorted_labels_load_1_reg_610 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal trunc_ln171_fu_288_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln171_reg_615 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal j_fu_292_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal j_reg_621 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln171_fu_298_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal freqs_0_V_4_fu_361_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal freqs_0_V_5_fu_377_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal freqs_0_V_6_fu_385_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln879_fu_454_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal select_ln879_1_fu_462_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln879_2_fu_470_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal local_cnt_V_1_fu_478_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln183_fu_532_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal icmp_ln182_fu_486_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_1_fu_540_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal sorted_distances_q0 : STD_LOGIC_VECTOR (5 downto 0);
    signal sorted_distances_q1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sorted_labels_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal sorted_labels_ce0 : STD_LOGIC;
    signal sorted_labels_we0 : STD_LOGIC;
    signal sorted_labels_ce1 : STD_LOGIC;
    signal sorted_labels_we1 : STD_LOGIC;
    signal sorted_labels_q1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_sort_knn_fu_221_ap_start : STD_LOGIC;
    signal grp_sort_knn_fu_221_ap_done : STD_LOGIC;
    signal grp_sort_knn_fu_221_ap_idle : STD_LOGIC;
    signal grp_sort_knn_fu_221_ap_ready : STD_LOGIC;
    signal grp_sort_knn_fu_221_knn_set_V_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sort_knn_fu_221_knn_set_V_ce0 : STD_LOGIC;
    signal grp_sort_knn_fu_221_sorted_distances_V_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sort_knn_fu_221_sorted_distances_V_ce0 : STD_LOGIC;
    signal grp_sort_knn_fu_221_sorted_distances_V_we0 : STD_LOGIC;
    signal grp_sort_knn_fu_221_sorted_distances_V_d0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_sort_knn_fu_221_sorted_distances_V_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sort_knn_fu_221_sorted_distances_V_ce1 : STD_LOGIC;
    signal grp_sort_knn_fu_221_sorted_distances_V_we1 : STD_LOGIC;
    signal grp_sort_knn_fu_221_sorted_distances_V_d1 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_sort_knn_fu_221_sorted_labels_V_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sort_knn_fu_221_sorted_labels_V_ce0 : STD_LOGIC;
    signal grp_sort_knn_fu_221_sorted_labels_V_we0 : STD_LOGIC;
    signal grp_sort_knn_fu_221_sorted_labels_V_d0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_sort_knn_fu_221_sorted_labels_V_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sort_knn_fu_221_sorted_labels_V_ce1 : STD_LOGIC;
    signal grp_sort_knn_fu_221_sorted_labels_V_we1 : STD_LOGIC;
    signal grp_sort_knn_fu_221_sorted_labels_V_d1 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_phi_mux_i_0_phi_fu_96_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal i_0_reg_92 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln164_fu_240_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal freqs_2_V_2_reg_103 : STD_LOGIC_VECTOR (3 downto 0);
    signal freqs_1_V_2_reg_113 : STD_LOGIC_VECTOR (3 downto 0);
    signal freqs_0_V_2_reg_123 : STD_LOGIC_VECTOR (3 downto 0);
    signal i3_0_reg_133 : STD_LOGIC_VECTOR (1 downto 0);
    signal freqs_2_V_3_reg_145 : STD_LOGIC_VECTOR (3 downto 0);
    signal freqs_1_V_3_reg_156 : STD_LOGIC_VECTOR (3 downto 0);
    signal freqs_0_V_reg_167 : STD_LOGIC_VECTOR (3 downto 0);
    signal t_V_reg_178 : STD_LOGIC_VECTOR (3 downto 0);
    signal j_0_in_reg_190 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_022_0_reg_199 : STD_LOGIC_VECTOR (3 downto 0);
    signal val_assign_reg_210 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_sort_knn_fu_221_ap_start_reg : STD_LOGIC := '0';
    signal zext_ln172_fu_283_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln172_fu_304_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln544_fu_546_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal freqs_0_V_0_fu_46 : STD_LOGIC_VECTOR (3 downto 0);
    signal freqs_1_V_0_fu_50 : STD_LOGIC_VECTOR (3 downto 0);
    signal freqs_2_V_0_fu_54 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_2_fu_309_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln321_1_fu_333_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln883_fu_321_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln321_fu_327_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln883_fu_347_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln883_fu_353_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln883_2_fu_369_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal freqs_0_V_3_fu_339_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln321_2_fu_404_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln321_3_fu_417_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln321_fu_409_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln321_2_fu_430_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln879_fu_393_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln321_1_fu_422_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln321_3_fu_438_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln321_4_fu_446_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal local_cnt_V_fu_398_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln895_1_fu_492_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_510_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln895_fu_498_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_510_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln895_fu_522_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal max_idx_V_fu_528_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_return_preg : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);

    component sort_knn IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        knn_set_V_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        knn_set_V_ce0 : OUT STD_LOGIC;
        knn_set_V_q0 : IN STD_LOGIC_VECTOR (5 downto 0);
        sorted_distances_V_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        sorted_distances_V_ce0 : OUT STD_LOGIC;
        sorted_distances_V_we0 : OUT STD_LOGIC;
        sorted_distances_V_d0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        sorted_distances_V_q0 : IN STD_LOGIC_VECTOR (5 downto 0);
        sorted_distances_V_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        sorted_distances_V_ce1 : OUT STD_LOGIC;
        sorted_distances_V_we1 : OUT STD_LOGIC;
        sorted_distances_V_d1 : OUT STD_LOGIC_VECTOR (5 downto 0);
        sorted_distances_V_q1 : IN STD_LOGIC_VECTOR (5 downto 0);
        sorted_labels_V_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        sorted_labels_V_ce0 : OUT STD_LOGIC;
        sorted_labels_V_we0 : OUT STD_LOGIC;
        sorted_labels_V_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        sorted_labels_V_q0 : IN STD_LOGIC_VECTOR (3 downto 0);
        sorted_labels_V_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        sorted_labels_V_ce1 : OUT STD_LOGIC;
        sorted_labels_V_we1 : OUT STD_LOGIC;
        sorted_labels_V_d1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        sorted_labels_V_q1 : IN STD_LOGIC_VECTOR (3 downto 0) );
    end component;


    component dut_mux_32_4_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (3 downto 0);
        din1 : IN STD_LOGIC_VECTOR (3 downto 0);
        din2 : IN STD_LOGIC_VECTOR (3 downto 0);
        din3 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (3 downto 0) );
    end component;


    component knn_vote_sorted_dbkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (5 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        address1 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (5 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component knn_vote_sorted_lcud IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (3 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        address1 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (3 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (3 downto 0) );
    end component;



begin
    sorted_distances_U : component knn_vote_sorted_dbkb
    generic map (
        DataWidth => 6,
        AddressRange => 30,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_sort_knn_fu_221_sorted_distances_V_address0,
        ce0 => grp_sort_knn_fu_221_sorted_distances_V_ce0,
        we0 => grp_sort_knn_fu_221_sorted_distances_V_we0,
        d0 => grp_sort_knn_fu_221_sorted_distances_V_d0,
        q0 => sorted_distances_q0,
        address1 => grp_sort_knn_fu_221_sorted_distances_V_address1,
        ce1 => grp_sort_knn_fu_221_sorted_distances_V_ce1,
        we1 => grp_sort_knn_fu_221_sorted_distances_V_we1,
        d1 => grp_sort_knn_fu_221_sorted_distances_V_d1,
        q1 => sorted_distances_q1);

    sorted_labels_U : component knn_vote_sorted_lcud
    generic map (
        DataWidth => 4,
        AddressRange => 30,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => sorted_labels_address0,
        ce0 => sorted_labels_ce0,
        we0 => sorted_labels_we0,
        d0 => grp_sort_knn_fu_221_sorted_labels_V_d0,
        q0 => sorted_labels_q0,
        address1 => grp_sort_knn_fu_221_sorted_labels_V_address1,
        ce1 => sorted_labels_ce1,
        we1 => sorted_labels_we1,
        d1 => grp_sort_knn_fu_221_sorted_labels_V_d1,
        q1 => sorted_labels_q1);

    grp_sort_knn_fu_221 : component sort_knn
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_sort_knn_fu_221_ap_start,
        ap_done => grp_sort_knn_fu_221_ap_done,
        ap_idle => grp_sort_knn_fu_221_ap_idle,
        ap_ready => grp_sort_knn_fu_221_ap_ready,
        knn_set_V_address0 => grp_sort_knn_fu_221_knn_set_V_address0,
        knn_set_V_ce0 => grp_sort_knn_fu_221_knn_set_V_ce0,
        knn_set_V_q0 => knn_set_V_q0,
        sorted_distances_V_address0 => grp_sort_knn_fu_221_sorted_distances_V_address0,
        sorted_distances_V_ce0 => grp_sort_knn_fu_221_sorted_distances_V_ce0,
        sorted_distances_V_we0 => grp_sort_knn_fu_221_sorted_distances_V_we0,
        sorted_distances_V_d0 => grp_sort_knn_fu_221_sorted_distances_V_d0,
        sorted_distances_V_q0 => sorted_distances_q0,
        sorted_distances_V_address1 => grp_sort_knn_fu_221_sorted_distances_V_address1,
        sorted_distances_V_ce1 => grp_sort_knn_fu_221_sorted_distances_V_ce1,
        sorted_distances_V_we1 => grp_sort_knn_fu_221_sorted_distances_V_we1,
        sorted_distances_V_d1 => grp_sort_knn_fu_221_sorted_distances_V_d1,
        sorted_distances_V_q1 => sorted_distances_q1,
        sorted_labels_V_address0 => grp_sort_knn_fu_221_sorted_labels_V_address0,
        sorted_labels_V_ce0 => grp_sort_knn_fu_221_sorted_labels_V_ce0,
        sorted_labels_V_we0 => grp_sort_knn_fu_221_sorted_labels_V_we0,
        sorted_labels_V_d0 => grp_sort_knn_fu_221_sorted_labels_V_d0,
        sorted_labels_V_q0 => sorted_labels_q0,
        sorted_labels_V_address1 => grp_sort_knn_fu_221_sorted_labels_V_address1,
        sorted_labels_V_ce1 => grp_sort_knn_fu_221_sorted_labels_V_ce1,
        sorted_labels_V_we1 => grp_sort_knn_fu_221_sorted_labels_V_we1,
        sorted_labels_V_d1 => grp_sort_knn_fu_221_sorted_labels_V_d1,
        sorted_labels_V_q1 => sorted_labels_q1);

    dut_mux_32_4_1_1_U4 : component dut_mux_32_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        din2_WIDTH => 4,
        din3_WIDTH => 2,
        dout_WIDTH => 4)
    port map (
        din0 => freqs_0_V_reg_167,
        din1 => freqs_1_V_3_reg_156,
        din2 => freqs_2_V_3_reg_145,
        din3 => i3_0_reg_133,
        dout => tmp_2_fu_309_p5);

    dut_mux_32_4_1_1_U5 : component dut_mux_32_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        din2_WIDTH => 4,
        din3_WIDTH => 2,
        dout_WIDTH => 4)
    port map (
        din0 => freqs_0_V_2_reg_123,
        din1 => freqs_1_V_2_reg_113,
        din2 => freqs_2_V_2_reg_103,
        din3 => tmp_1_fu_510_p4,
        dout => tmp_1_fu_510_p5);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_return_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_preg <= ap_const_lv4_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                    ap_return_preg <= sorted_labels_q0;
                end if; 
            end if;
        end if;
    end process;


    grp_sort_knn_fu_221_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_sort_knn_fu_221_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_sort_knn_fu_221_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_sort_knn_fu_221_ap_ready = ap_const_logic_1)) then 
                    grp_sort_knn_fu_221_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    freqs_0_V_2_reg_123_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln164_fu_240_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                freqs_0_V_2_reg_123 <= freqs_0_V_0_fu_46;
            elsif (((icmp_ln171_fu_298_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                freqs_0_V_2_reg_123 <= freqs_0_V_6_fu_385_p3;
            end if; 
        end if;
    end process;

    freqs_0_V_reg_167_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                freqs_0_V_reg_167 <= select_ln879_2_fu_470_p3;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                freqs_0_V_reg_167 <= freqs_0_V_2_reg_123;
            end if; 
        end if;
    end process;

    freqs_1_V_2_reg_113_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln164_fu_240_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                freqs_1_V_2_reg_113 <= freqs_1_V_0_fu_50;
            elsif (((icmp_ln171_fu_298_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                freqs_1_V_2_reg_113 <= freqs_0_V_5_fu_377_p3;
            end if; 
        end if;
    end process;

    freqs_1_V_3_reg_156_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                freqs_1_V_3_reg_156 <= select_ln879_1_fu_462_p3;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                freqs_1_V_3_reg_156 <= freqs_1_V_2_reg_113;
            end if; 
        end if;
    end process;

    freqs_2_V_2_reg_103_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln164_fu_240_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                freqs_2_V_2_reg_103 <= freqs_2_V_0_fu_54;
            elsif (((icmp_ln171_fu_298_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                freqs_2_V_2_reg_103 <= freqs_0_V_4_fu_361_p3;
            end if; 
        end if;
    end process;

    freqs_2_V_3_reg_145_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                freqs_2_V_3_reg_145 <= select_ln879_fu_454_p3;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                freqs_2_V_3_reg_145 <= freqs_2_V_2_reg_103;
            end if; 
        end if;
    end process;

    i3_0_reg_133_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln164_fu_240_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                i3_0_reg_133 <= ap_const_lv2_0;
            elsif (((icmp_ln171_fu_298_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                i3_0_reg_133 <= i_2_reg_600;
            end if; 
        end if;
    end process;

    i_0_reg_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln164_fu_240_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                i_0_reg_92 <= i_fu_246_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_sort_knn_fu_221_ap_done = ap_const_logic_1))) then 
                i_0_reg_92 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    j_0_in_reg_190_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                j_0_in_reg_190 <= j_reg_621;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                j_0_in_reg_190 <= zext_ln169_reg_592;
            end if; 
        end if;
    end process;

    p_022_0_reg_199_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln169_fu_271_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                p_022_0_reg_199 <= ap_const_lv4_0;
            elsif (((icmp_ln182_fu_486_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
                p_022_0_reg_199 <= select_ln183_fu_532_p3;
            end if; 
        end if;
    end process;

    t_V_reg_178_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                t_V_reg_178 <= local_cnt_V_1_fu_478_p3;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                t_V_reg_178 <= ap_const_lv4_1;
            end if; 
        end if;
    end process;

    val_assign_reg_210_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln169_fu_271_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                val_assign_reg_210 <= ap_const_lv2_1;
            elsif (((icmp_ln182_fu_486_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
                val_assign_reg_210 <= i_1_fu_540_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                i_2_reg_600 <= i_2_fu_277_p2;
                    zext_ln169_reg_592(1 downto 0) <= zext_ln169_fu_267_p1(1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                j_reg_621 <= j_fu_292_p2;
                trunc_ln171_reg_615 <= trunc_ln171_fu_288_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                sorted_labels_load_1_reg_610 <= sorted_labels_q0;
            end if;
        end if;
    end process;
    zext_ln169_reg_592(31 downto 2) <= "000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state3, ap_CS_fsm_state4, icmp_ln169_fu_271_p2, ap_CS_fsm_state6, icmp_ln171_fu_298_p2, ap_CS_fsm_state8, icmp_ln182_fu_486_p2, grp_sort_knn_fu_221_ap_done, ap_CS_fsm_state2, icmp_ln164_fu_240_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_sort_knn_fu_221_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln164_fu_240_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((icmp_ln169_fu_271_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((icmp_ln171_fu_298_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state8 => 
                if (((icmp_ln182_fu_486_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_phi_mux_i_0_phi_fu_96_p4 <= i_0_reg_92;

    ap_ready_assign_proc : process(ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_assign_proc : process(sorted_labels_q0, ap_return_preg, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            ap_return <= sorted_labels_q0;
        else 
            ap_return <= ap_return_preg;
        end if; 
    end process;

    freqs_0_V_0_fu_46 <= ap_const_lv4_F;
    freqs_0_V_3_fu_339_p3 <= 
        t_V_reg_178 when (icmp_ln321_1_fu_333_p2(0) = '1') else 
        freqs_0_V_reg_167;
    freqs_0_V_4_fu_361_p3 <= 
        freqs_2_V_3_reg_145 when (or_ln883_fu_347_p2(0) = '1') else 
        select_ln883_fu_353_p3;
    freqs_0_V_5_fu_377_p3 <= 
        freqs_1_V_3_reg_156 when (or_ln883_fu_347_p2(0) = '1') else 
        select_ln883_2_fu_369_p3;
    freqs_0_V_6_fu_385_p3 <= 
        freqs_0_V_reg_167 when (icmp_ln883_fu_321_p2(0) = '1') else 
        freqs_0_V_3_fu_339_p3;
    freqs_1_V_0_fu_50 <= ap_const_lv4_F;
    freqs_2_V_0_fu_54 <= ap_const_lv4_F;
    grp_sort_knn_fu_221_ap_start <= grp_sort_knn_fu_221_ap_start_reg;
    i_1_fu_540_p2 <= std_logic_vector(unsigned(ap_const_lv2_1) + unsigned(val_assign_reg_210));
    i_2_fu_277_p2 <= std_logic_vector(unsigned(i3_0_reg_133) + unsigned(ap_const_lv2_1));
    i_fu_246_p2 <= std_logic_vector(unsigned(i_0_reg_92) + unsigned(ap_const_lv2_1));
    icmp_ln164_fu_240_p2 <= "1" when (i_0_reg_92 = ap_const_lv2_3) else "0";
    icmp_ln169_fu_271_p2 <= "1" when (i3_0_reg_133 = ap_const_lv2_3) else "0";
    icmp_ln171_fu_298_p2 <= "1" when (j_0_in_reg_190 = ap_const_lv32_2) else "0";
    icmp_ln182_fu_486_p2 <= "1" when (val_assign_reg_210 = ap_const_lv2_3) else "0";
    icmp_ln321_1_fu_333_p2 <= "1" when (i3_0_reg_133 = ap_const_lv2_0) else "0";
    icmp_ln321_2_fu_404_p2 <= "1" when (trunc_ln171_reg_615 = ap_const_lv2_0) else "0";
    icmp_ln321_3_fu_417_p2 <= "1" when (trunc_ln171_reg_615 = ap_const_lv2_3) else "0";
    icmp_ln321_fu_327_p2 <= "1" when (i3_0_reg_133 = ap_const_lv2_1) else "0";
    icmp_ln879_fu_393_p2 <= "1" when (sorted_labels_load_1_reg_610 = sorted_labels_q0) else "0";
    icmp_ln883_fu_321_p2 <= "1" when (tmp_2_fu_309_p5 = ap_const_lv4_0) else "0";
    icmp_ln895_1_fu_492_p2 <= "1" when (val_assign_reg_210 = ap_const_lv2_1) else "0";
    icmp_ln895_fu_522_p2 <= "1" when (unsigned(select_ln895_fu_498_p3) > unsigned(tmp_1_fu_510_p5)) else "0";
    j_fu_292_p2 <= std_logic_vector(unsigned(ap_const_lv32_1) + unsigned(j_0_in_reg_190));
    knn_set_V_address0 <= grp_sort_knn_fu_221_knn_set_V_address0;
    knn_set_V_ce0 <= grp_sort_knn_fu_221_knn_set_V_ce0;
    local_cnt_V_1_fu_478_p3 <= 
        local_cnt_V_fu_398_p2 when (icmp_ln879_fu_393_p2(0) = '1') else 
        t_V_reg_178;
    local_cnt_V_fu_398_p2 <= std_logic_vector(unsigned(t_V_reg_178) + unsigned(ap_const_lv4_1));
    max_idx_V_fu_528_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(val_assign_reg_210),4));
    or_ln883_fu_347_p2 <= (icmp_ln883_fu_321_p2 or icmp_ln321_1_fu_333_p2);
    select_ln183_fu_532_p3 <= 
        max_idx_V_fu_528_p1 when (icmp_ln895_fu_522_p2(0) = '1') else 
        p_022_0_reg_199;
    select_ln321_1_fu_422_p3 <= 
        freqs_2_V_3_reg_145 when (icmp_ln321_3_fu_417_p2(0) = '1') else 
        select_ln321_fu_409_p3;
    select_ln321_2_fu_430_p3 <= 
        ap_const_lv4_0 when (icmp_ln321_2_fu_404_p2(0) = '1') else 
        freqs_1_V_3_reg_156;
    select_ln321_3_fu_438_p3 <= 
        freqs_1_V_3_reg_156 when (icmp_ln321_3_fu_417_p2(0) = '1') else 
        select_ln321_2_fu_430_p3;
    select_ln321_4_fu_446_p3 <= 
        ap_const_lv4_0 when (icmp_ln321_3_fu_417_p2(0) = '1') else 
        freqs_0_V_reg_167;
    select_ln321_fu_409_p3 <= 
        freqs_2_V_3_reg_145 when (icmp_ln321_2_fu_404_p2(0) = '1') else 
        ap_const_lv4_0;
    select_ln879_1_fu_462_p3 <= 
        select_ln321_3_fu_438_p3 when (icmp_ln879_fu_393_p2(0) = '1') else 
        freqs_1_V_3_reg_156;
    select_ln879_2_fu_470_p3 <= 
        select_ln321_4_fu_446_p3 when (icmp_ln879_fu_393_p2(0) = '1') else 
        freqs_0_V_reg_167;
    select_ln879_fu_454_p3 <= 
        select_ln321_1_fu_422_p3 when (icmp_ln879_fu_393_p2(0) = '1') else 
        freqs_2_V_3_reg_145;
    select_ln883_2_fu_369_p3 <= 
        t_V_reg_178 when (icmp_ln321_fu_327_p2(0) = '1') else 
        freqs_1_V_3_reg_156;
    select_ln883_fu_353_p3 <= 
        freqs_2_V_3_reg_145 when (icmp_ln321_fu_327_p2(0) = '1') else 
        t_V_reg_178;
    select_ln895_fu_498_p3 <= 
        freqs_1_V_2_reg_113 when (icmp_ln895_1_fu_492_p2(0) = '1') else 
        freqs_2_V_2_reg_103;
        sext_ln172_fu_304_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(j_fu_292_p2),64));


    sorted_labels_address0_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state8, grp_sort_knn_fu_221_sorted_labels_V_address0, ap_CS_fsm_state2, zext_ln172_fu_283_p1, sext_ln172_fu_304_p1, zext_ln544_fu_546_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            sorted_labels_address0 <= zext_ln544_fu_546_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            sorted_labels_address0 <= sext_ln172_fu_304_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            sorted_labels_address0 <= zext_ln172_fu_283_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            sorted_labels_address0 <= grp_sort_knn_fu_221_sorted_labels_V_address0;
        else 
            sorted_labels_address0 <= "XXXXX";
        end if; 
    end process;


    sorted_labels_ce0_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state8, grp_sort_knn_fu_221_sorted_labels_V_ce0, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            sorted_labels_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            sorted_labels_ce0 <= grp_sort_knn_fu_221_sorted_labels_V_ce0;
        else 
            sorted_labels_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    sorted_labels_ce1_assign_proc : process(grp_sort_knn_fu_221_sorted_labels_V_ce1, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            sorted_labels_ce1 <= grp_sort_knn_fu_221_sorted_labels_V_ce1;
        else 
            sorted_labels_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    sorted_labels_we0_assign_proc : process(grp_sort_knn_fu_221_sorted_labels_V_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            sorted_labels_we0 <= grp_sort_knn_fu_221_sorted_labels_V_we0;
        else 
            sorted_labels_we0 <= ap_const_logic_0;
        end if; 
    end process;


    sorted_labels_we1_assign_proc : process(grp_sort_knn_fu_221_sorted_labels_V_we1, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            sorted_labels_we1 <= grp_sort_knn_fu_221_sorted_labels_V_we1;
        else 
            sorted_labels_we1 <= ap_const_logic_0;
        end if; 
    end process;

    tmp_1_fu_510_p4 <= p_022_0_reg_199(2 - 1 downto 0);
    trunc_ln171_fu_288_p1 <= j_0_in_reg_190(2 - 1 downto 0);
    zext_ln169_fu_267_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i3_0_reg_133),32));
    zext_ln172_fu_283_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i3_0_reg_133),64));
    zext_ln544_fu_546_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_022_0_reg_199),64));
end behav;
