// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "knn_vote.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic knn_vote::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic knn_vote::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<9> knn_vote::ap_ST_fsm_state1 = "1";
const sc_lv<9> knn_vote::ap_ST_fsm_state2 = "10";
const sc_lv<9> knn_vote::ap_ST_fsm_state3 = "100";
const sc_lv<9> knn_vote::ap_ST_fsm_state4 = "1000";
const sc_lv<9> knn_vote::ap_ST_fsm_state5 = "10000";
const sc_lv<9> knn_vote::ap_ST_fsm_state6 = "100000";
const sc_lv<9> knn_vote::ap_ST_fsm_state7 = "1000000";
const sc_lv<9> knn_vote::ap_ST_fsm_state8 = "10000000";
const sc_lv<9> knn_vote::ap_ST_fsm_state9 = "100000000";
const sc_lv<32> knn_vote::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> knn_vote::ap_const_lv32_2 = "10";
const sc_lv<32> knn_vote::ap_const_lv32_3 = "11";
const sc_lv<1> knn_vote::ap_const_lv1_0 = "0";
const sc_lv<32> knn_vote::ap_const_lv32_4 = "100";
const sc_lv<32> knn_vote::ap_const_lv32_5 = "101";
const sc_lv<1> knn_vote::ap_const_lv1_1 = "1";
const sc_lv<32> knn_vote::ap_const_lv32_6 = "110";
const sc_lv<32> knn_vote::ap_const_lv32_7 = "111";
const sc_lv<2> knn_vote::ap_const_lv2_0 = "00";
const sc_lv<32> knn_vote::ap_const_lv32_1 = "1";
const sc_lv<4> knn_vote::ap_const_lv4_1 = "1";
const sc_lv<4> knn_vote::ap_const_lv4_0 = "0000";
const sc_lv<2> knn_vote::ap_const_lv2_1 = "1";
const sc_lv<4> knn_vote::ap_const_lv4_F = "1111";
const sc_lv<2> knn_vote::ap_const_lv2_3 = "11";
const sc_lv<32> knn_vote::ap_const_lv32_8 = "1000";
const bool knn_vote::ap_const_boolean_1 = true;

knn_vote::knn_vote(sc_module_name name) : sc_module(name), mVcdFile(0) {
    sorted_distances_U = new knn_vote_sorted_dbkb("sorted_distances_U");
    sorted_distances_U->clk(ap_clk);
    sorted_distances_U->reset(ap_rst);
    sorted_distances_U->address0(grp_sort_knn_fu_461_sorted_distances_V_address0);
    sorted_distances_U->ce0(grp_sort_knn_fu_461_sorted_distances_V_ce0);
    sorted_distances_U->we0(grp_sort_knn_fu_461_sorted_distances_V_we0);
    sorted_distances_U->d0(grp_sort_knn_fu_461_sorted_distances_V_d0);
    sorted_distances_U->q0(sorted_distances_q0);
    sorted_distances_U->address1(grp_sort_knn_fu_461_sorted_distances_V_address1);
    sorted_distances_U->ce1(grp_sort_knn_fu_461_sorted_distances_V_ce1);
    sorted_distances_U->we1(grp_sort_knn_fu_461_sorted_distances_V_we1);
    sorted_distances_U->d1(grp_sort_knn_fu_461_sorted_distances_V_d1);
    sorted_distances_U->q1(sorted_distances_q1);
    sorted_labels_U = new knn_vote_sorted_lcud("sorted_labels_U");
    sorted_labels_U->clk(ap_clk);
    sorted_labels_U->reset(ap_rst);
    sorted_labels_U->address0(sorted_labels_address0);
    sorted_labels_U->ce0(sorted_labels_ce0);
    sorted_labels_U->we0(sorted_labels_we0);
    sorted_labels_U->d0(grp_sort_knn_fu_461_sorted_labels_V_d0);
    sorted_labels_U->q0(sorted_labels_q0);
    sorted_labels_U->address1(grp_sort_knn_fu_461_sorted_labels_V_address1);
    sorted_labels_U->ce1(sorted_labels_ce1);
    sorted_labels_U->we1(sorted_labels_we1);
    sorted_labels_U->d1(grp_sort_knn_fu_461_sorted_labels_V_d1);
    sorted_labels_U->q1(sorted_labels_q1);
    grp_sort_knn_fu_461 = new sort_knn("grp_sort_knn_fu_461");
    grp_sort_knn_fu_461->ap_clk(ap_clk);
    grp_sort_knn_fu_461->ap_rst(ap_rst);
    grp_sort_knn_fu_461->ap_start(grp_sort_knn_fu_461_ap_start);
    grp_sort_knn_fu_461->ap_done(grp_sort_knn_fu_461_ap_done);
    grp_sort_knn_fu_461->ap_idle(grp_sort_knn_fu_461_ap_idle);
    grp_sort_knn_fu_461->ap_ready(grp_sort_knn_fu_461_ap_ready);
    grp_sort_knn_fu_461->knn_set_0_0_V_read(knn_set_0_0_V_read);
    grp_sort_knn_fu_461->knn_set_0_1_V_read(knn_set_0_1_V_read);
    grp_sort_knn_fu_461->knn_set_0_2_V_read(knn_set_0_2_V_read);
    grp_sort_knn_fu_461->knn_set_1_0_V_read(knn_set_1_0_V_read);
    grp_sort_knn_fu_461->knn_set_1_1_V_read(knn_set_1_1_V_read);
    grp_sort_knn_fu_461->knn_set_1_2_V_read(knn_set_1_2_V_read);
    grp_sort_knn_fu_461->knn_set_2_0_V_read(knn_set_2_0_V_read);
    grp_sort_knn_fu_461->knn_set_2_1_V_read(knn_set_2_1_V_read);
    grp_sort_knn_fu_461->knn_set_2_2_V_read(knn_set_2_2_V_read);
    grp_sort_knn_fu_461->knn_set_3_0_V_read(knn_set_3_0_V_read);
    grp_sort_knn_fu_461->knn_set_3_1_V_read(knn_set_3_1_V_read);
    grp_sort_knn_fu_461->knn_set_3_2_V_read(knn_set_3_2_V_read);
    grp_sort_knn_fu_461->knn_set_4_0_V_read(knn_set_4_0_V_read);
    grp_sort_knn_fu_461->knn_set_4_1_V_read(knn_set_4_1_V_read);
    grp_sort_knn_fu_461->knn_set_4_2_V_read(knn_set_4_2_V_read);
    grp_sort_knn_fu_461->knn_set_5_0_V_read(knn_set_5_0_V_read);
    grp_sort_knn_fu_461->knn_set_5_1_V_read(knn_set_5_1_V_read);
    grp_sort_knn_fu_461->knn_set_5_2_V_read(knn_set_5_2_V_read);
    grp_sort_knn_fu_461->knn_set_6_0_V_read(knn_set_6_0_V_read);
    grp_sort_knn_fu_461->knn_set_6_1_V_read(knn_set_6_1_V_read);
    grp_sort_knn_fu_461->knn_set_6_2_V_read(knn_set_6_2_V_read);
    grp_sort_knn_fu_461->knn_set_7_0_V_read(knn_set_7_0_V_read);
    grp_sort_knn_fu_461->knn_set_7_1_V_read(knn_set_7_1_V_read);
    grp_sort_knn_fu_461->knn_set_7_2_V_read(knn_set_7_2_V_read);
    grp_sort_knn_fu_461->knn_set_8_0_V_read(knn_set_8_0_V_read);
    grp_sort_knn_fu_461->knn_set_8_1_V_read(knn_set_8_1_V_read);
    grp_sort_knn_fu_461->knn_set_8_2_V_read(knn_set_8_2_V_read);
    grp_sort_knn_fu_461->knn_set_9_0_V_read(knn_set_9_0_V_read);
    grp_sort_knn_fu_461->knn_set_9_1_V_read(knn_set_9_1_V_read);
    grp_sort_knn_fu_461->knn_set_9_2_V_read(knn_set_9_2_V_read);
    grp_sort_knn_fu_461->sorted_distances_V_address0(grp_sort_knn_fu_461_sorted_distances_V_address0);
    grp_sort_knn_fu_461->sorted_distances_V_ce0(grp_sort_knn_fu_461_sorted_distances_V_ce0);
    grp_sort_knn_fu_461->sorted_distances_V_we0(grp_sort_knn_fu_461_sorted_distances_V_we0);
    grp_sort_knn_fu_461->sorted_distances_V_d0(grp_sort_knn_fu_461_sorted_distances_V_d0);
    grp_sort_knn_fu_461->sorted_distances_V_q0(sorted_distances_q0);
    grp_sort_knn_fu_461->sorted_distances_V_address1(grp_sort_knn_fu_461_sorted_distances_V_address1);
    grp_sort_knn_fu_461->sorted_distances_V_ce1(grp_sort_knn_fu_461_sorted_distances_V_ce1);
    grp_sort_knn_fu_461->sorted_distances_V_we1(grp_sort_knn_fu_461_sorted_distances_V_we1);
    grp_sort_knn_fu_461->sorted_distances_V_d1(grp_sort_knn_fu_461_sorted_distances_V_d1);
    grp_sort_knn_fu_461->sorted_distances_V_q1(sorted_distances_q1);
    grp_sort_knn_fu_461->sorted_labels_V_address0(grp_sort_knn_fu_461_sorted_labels_V_address0);
    grp_sort_knn_fu_461->sorted_labels_V_ce0(grp_sort_knn_fu_461_sorted_labels_V_ce0);
    grp_sort_knn_fu_461->sorted_labels_V_we0(grp_sort_knn_fu_461_sorted_labels_V_we0);
    grp_sort_knn_fu_461->sorted_labels_V_d0(grp_sort_knn_fu_461_sorted_labels_V_d0);
    grp_sort_knn_fu_461->sorted_labels_V_q0(sorted_labels_q0);
    grp_sort_knn_fu_461->sorted_labels_V_address1(grp_sort_knn_fu_461_sorted_labels_V_address1);
    grp_sort_knn_fu_461->sorted_labels_V_ce1(grp_sort_knn_fu_461_sorted_labels_V_ce1);
    grp_sort_knn_fu_461->sorted_labels_V_we1(grp_sort_knn_fu_461_sorted_labels_V_we1);
    grp_sort_knn_fu_461->sorted_labels_V_d1(grp_sort_knn_fu_461_sorted_labels_V_d1);
    grp_sort_knn_fu_461->sorted_labels_V_q1(sorted_labels_q1);
    dut_mux_32_4_1_1_U52 = new dut_mux_32_4_1_1<1,1,4,4,4,2,4>("dut_mux_32_4_1_1_U52");
    dut_mux_32_4_1_1_U52->din0(freqs_0_V_reg_407);
    dut_mux_32_4_1_1_U52->din1(freqs_1_V_3_reg_396);
    dut_mux_32_4_1_1_U52->din2(freqs_2_V_3_reg_385);
    dut_mux_32_4_1_1_U52->din3(i3_0_reg_373);
    dut_mux_32_4_1_1_U52->dout(tmp_4_fu_607_p5);
    dut_mux_32_4_1_1_U53 = new dut_mux_32_4_1_1<1,1,4,4,4,2,4>("dut_mux_32_4_1_1_U53");
    dut_mux_32_4_1_1_U53->din0(freqs_0_V_2_reg_363);
    dut_mux_32_4_1_1_U53->din1(freqs_1_V_2_reg_353);
    dut_mux_32_4_1_1_U53->din2(freqs_2_V_2_reg_343);
    dut_mux_32_4_1_1_U53->din3(tmp_3_fu_808_p4);
    dut_mux_32_4_1_1_U53->dout(tmp_3_fu_808_p5);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_phi_mux_i_0_phi_fu_336_p4);
    sensitive << ( i_0_reg_332 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_ap_return);
    sensitive << ( sorted_labels_q0 );
    sensitive << ( ap_return_preg );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_freqs_0_V_0_fu_106);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_phi_mux_i_0_phi_fu_336_p4 );
    sensitive << ( icmp_ln164_fu_538_p2 );

    SC_METHOD(thread_freqs_0_V_3_fu_637_p3);
    sensitive << ( freqs_0_V_reg_407 );
    sensitive << ( t_V_reg_418 );
    sensitive << ( icmp_ln321_1_fu_631_p2 );

    SC_METHOD(thread_freqs_0_V_4_fu_659_p3);
    sensitive << ( freqs_2_V_3_reg_385 );
    sensitive << ( or_ln883_fu_645_p2 );
    sensitive << ( select_ln883_fu_651_p3 );

    SC_METHOD(thread_freqs_0_V_5_fu_675_p3);
    sensitive << ( freqs_1_V_3_reg_396 );
    sensitive << ( or_ln883_fu_645_p2 );
    sensitive << ( select_ln883_2_fu_667_p3 );

    SC_METHOD(thread_freqs_0_V_6_fu_683_p3);
    sensitive << ( freqs_0_V_reg_407 );
    sensitive << ( icmp_ln883_fu_619_p2 );
    sensitive << ( freqs_0_V_3_fu_637_p3 );

    SC_METHOD(thread_freqs_1_V_0_fu_110);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_phi_mux_i_0_phi_fu_336_p4 );
    sensitive << ( icmp_ln164_fu_538_p2 );

    SC_METHOD(thread_freqs_2_V_0_fu_114);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_phi_mux_i_0_phi_fu_336_p4 );
    sensitive << ( icmp_ln164_fu_538_p2 );

    SC_METHOD(thread_grp_sort_knn_fu_461_ap_start);
    sensitive << ( grp_sort_knn_fu_461_ap_start_reg );

    SC_METHOD(thread_i_2_fu_838_p2);
    sensitive << ( val_assign_reg_450 );

    SC_METHOD(thread_i_3_fu_575_p2);
    sensitive << ( i3_0_reg_373 );

    SC_METHOD(thread_i_fu_544_p2);
    sensitive << ( i_0_reg_332 );

    SC_METHOD(thread_icmp_ln164_fu_538_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( i_0_reg_332 );

    SC_METHOD(thread_icmp_ln169_fu_569_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( i3_0_reg_373 );

    SC_METHOD(thread_icmp_ln171_fu_596_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( j_0_in_reg_430 );

    SC_METHOD(thread_icmp_ln182_fu_784_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( val_assign_reg_450 );

    SC_METHOD(thread_icmp_ln321_1_fu_631_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln171_fu_596_p2 );
    sensitive << ( i3_0_reg_373 );

    SC_METHOD(thread_icmp_ln321_2_fu_702_p2);
    sensitive << ( trunc_ln171_reg_1063 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_icmp_ln321_3_fu_715_p2);
    sensitive << ( trunc_ln171_reg_1063 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_icmp_ln321_fu_625_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln171_fu_596_p2 );
    sensitive << ( i3_0_reg_373 );

    SC_METHOD(thread_icmp_ln879_fu_691_p2);
    sensitive << ( sorted_labels_q0 );
    sensitive << ( sorted_labels_load_1_reg_1058 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_icmp_ln883_fu_619_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln171_fu_596_p2 );
    sensitive << ( tmp_4_fu_607_p5 );

    SC_METHOD(thread_icmp_ln895_2_fu_790_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln182_fu_784_p2 );
    sensitive << ( val_assign_reg_450 );

    SC_METHOD(thread_icmp_ln895_fu_820_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln182_fu_784_p2 );
    sensitive << ( select_ln895_fu_796_p3 );
    sensitive << ( tmp_3_fu_808_p5 );

    SC_METHOD(thread_j_fu_590_p2);
    sensitive << ( j_0_in_reg_430 );

    SC_METHOD(thread_local_cnt_V_1_fu_776_p3);
    sensitive << ( t_V_reg_418 );
    sensitive << ( icmp_ln879_fu_691_p2 );
    sensitive << ( local_cnt_V_fu_696_p2 );

    SC_METHOD(thread_local_cnt_V_fu_696_p2);
    sensitive << ( t_V_reg_418 );

    SC_METHOD(thread_max_idx_V_fu_826_p1);
    sensitive << ( val_assign_reg_450 );

    SC_METHOD(thread_or_ln883_fu_645_p2);
    sensitive << ( icmp_ln321_1_fu_631_p2 );
    sensitive << ( icmp_ln883_fu_619_p2 );

    SC_METHOD(thread_select_ln183_fu_830_p3);
    sensitive << ( p_022_0_reg_439 );
    sensitive << ( icmp_ln895_fu_820_p2 );
    sensitive << ( max_idx_V_fu_826_p1 );

    SC_METHOD(thread_select_ln321_1_fu_720_p3);
    sensitive << ( freqs_2_V_3_reg_385 );
    sensitive << ( icmp_ln321_3_fu_715_p2 );
    sensitive << ( select_ln321_fu_707_p3 );

    SC_METHOD(thread_select_ln321_2_fu_728_p3);
    sensitive << ( freqs_1_V_3_reg_396 );
    sensitive << ( icmp_ln321_2_fu_702_p2 );

    SC_METHOD(thread_select_ln321_3_fu_736_p3);
    sensitive << ( freqs_1_V_3_reg_396 );
    sensitive << ( icmp_ln321_3_fu_715_p2 );
    sensitive << ( select_ln321_2_fu_728_p3 );

    SC_METHOD(thread_select_ln321_4_fu_744_p3);
    sensitive << ( freqs_0_V_reg_407 );
    sensitive << ( icmp_ln321_3_fu_715_p2 );

    SC_METHOD(thread_select_ln321_fu_707_p3);
    sensitive << ( freqs_2_V_3_reg_385 );
    sensitive << ( icmp_ln321_2_fu_702_p2 );

    SC_METHOD(thread_select_ln879_1_fu_760_p3);
    sensitive << ( freqs_1_V_3_reg_396 );
    sensitive << ( icmp_ln879_fu_691_p2 );
    sensitive << ( select_ln321_3_fu_736_p3 );

    SC_METHOD(thread_select_ln879_2_fu_768_p3);
    sensitive << ( freqs_0_V_reg_407 );
    sensitive << ( icmp_ln879_fu_691_p2 );
    sensitive << ( select_ln321_4_fu_744_p3 );

    SC_METHOD(thread_select_ln879_fu_752_p3);
    sensitive << ( freqs_2_V_3_reg_385 );
    sensitive << ( icmp_ln879_fu_691_p2 );
    sensitive << ( select_ln321_1_fu_720_p3 );

    SC_METHOD(thread_select_ln883_2_fu_667_p3);
    sensitive << ( freqs_1_V_3_reg_396 );
    sensitive << ( t_V_reg_418 );
    sensitive << ( icmp_ln321_fu_625_p2 );

    SC_METHOD(thread_select_ln883_fu_651_p3);
    sensitive << ( freqs_2_V_3_reg_385 );
    sensitive << ( t_V_reg_418 );
    sensitive << ( icmp_ln321_fu_625_p2 );

    SC_METHOD(thread_select_ln895_fu_796_p3);
    sensitive << ( freqs_2_V_2_reg_343 );
    sensitive << ( freqs_1_V_2_reg_353 );
    sensitive << ( icmp_ln895_2_fu_790_p2 );

    SC_METHOD(thread_sext_ln172_fu_602_p1);
    sensitive << ( j_fu_590_p2 );

    SC_METHOD(thread_sorted_labels_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( grp_sort_knn_fu_461_sorted_labels_V_address0 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln172_fu_581_p1 );
    sensitive << ( sext_ln172_fu_602_p1 );
    sensitive << ( zext_ln544_fu_844_p1 );

    SC_METHOD(thread_sorted_labels_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( grp_sort_knn_fu_461_sorted_labels_V_ce0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_sorted_labels_ce1);
    sensitive << ( grp_sort_knn_fu_461_sorted_labels_V_ce1 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_sorted_labels_we0);
    sensitive << ( grp_sort_knn_fu_461_sorted_labels_V_we0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_sorted_labels_we1);
    sensitive << ( grp_sort_knn_fu_461_sorted_labels_V_we1 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_tmp_3_fu_808_p4);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( p_022_0_reg_439 );

    SC_METHOD(thread_trunc_ln171_fu_586_p1);
    sensitive << ( j_0_in_reg_430 );

    SC_METHOD(thread_zext_ln169_fu_565_p1);
    sensitive << ( i3_0_reg_373 );

    SC_METHOD(thread_zext_ln172_fu_581_p1);
    sensitive << ( i3_0_reg_373 );

    SC_METHOD(thread_zext_ln544_fu_844_p1);
    sensitive << ( p_022_0_reg_439 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln169_fu_569_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln171_fu_596_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln182_fu_784_p2 );
    sensitive << ( grp_sort_knn_fu_461_ap_done );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln164_fu_538_p2 );

    ap_CS_fsm = "000000001";
    grp_sort_knn_fu_461_ap_start_reg = SC_LOGIC_0;
    ap_return_preg = "0000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "knn_vote_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, knn_set_0_0_V_read, "(port)knn_set_0_0_V_read");
    sc_trace(mVcdFile, knn_set_0_1_V_read, "(port)knn_set_0_1_V_read");
    sc_trace(mVcdFile, knn_set_0_2_V_read, "(port)knn_set_0_2_V_read");
    sc_trace(mVcdFile, knn_set_1_0_V_read, "(port)knn_set_1_0_V_read");
    sc_trace(mVcdFile, knn_set_1_1_V_read, "(port)knn_set_1_1_V_read");
    sc_trace(mVcdFile, knn_set_1_2_V_read, "(port)knn_set_1_2_V_read");
    sc_trace(mVcdFile, knn_set_2_0_V_read, "(port)knn_set_2_0_V_read");
    sc_trace(mVcdFile, knn_set_2_1_V_read, "(port)knn_set_2_1_V_read");
    sc_trace(mVcdFile, knn_set_2_2_V_read, "(port)knn_set_2_2_V_read");
    sc_trace(mVcdFile, knn_set_3_0_V_read, "(port)knn_set_3_0_V_read");
    sc_trace(mVcdFile, knn_set_3_1_V_read, "(port)knn_set_3_1_V_read");
    sc_trace(mVcdFile, knn_set_3_2_V_read, "(port)knn_set_3_2_V_read");
    sc_trace(mVcdFile, knn_set_4_0_V_read, "(port)knn_set_4_0_V_read");
    sc_trace(mVcdFile, knn_set_4_1_V_read, "(port)knn_set_4_1_V_read");
    sc_trace(mVcdFile, knn_set_4_2_V_read, "(port)knn_set_4_2_V_read");
    sc_trace(mVcdFile, knn_set_5_0_V_read, "(port)knn_set_5_0_V_read");
    sc_trace(mVcdFile, knn_set_5_1_V_read, "(port)knn_set_5_1_V_read");
    sc_trace(mVcdFile, knn_set_5_2_V_read, "(port)knn_set_5_2_V_read");
    sc_trace(mVcdFile, knn_set_6_0_V_read, "(port)knn_set_6_0_V_read");
    sc_trace(mVcdFile, knn_set_6_1_V_read, "(port)knn_set_6_1_V_read");
    sc_trace(mVcdFile, knn_set_6_2_V_read, "(port)knn_set_6_2_V_read");
    sc_trace(mVcdFile, knn_set_7_0_V_read, "(port)knn_set_7_0_V_read");
    sc_trace(mVcdFile, knn_set_7_1_V_read, "(port)knn_set_7_1_V_read");
    sc_trace(mVcdFile, knn_set_7_2_V_read, "(port)knn_set_7_2_V_read");
    sc_trace(mVcdFile, knn_set_8_0_V_read, "(port)knn_set_8_0_V_read");
    sc_trace(mVcdFile, knn_set_8_1_V_read, "(port)knn_set_8_1_V_read");
    sc_trace(mVcdFile, knn_set_8_2_V_read, "(port)knn_set_8_2_V_read");
    sc_trace(mVcdFile, knn_set_9_0_V_read, "(port)knn_set_9_0_V_read");
    sc_trace(mVcdFile, knn_set_9_1_V_read, "(port)knn_set_9_1_V_read");
    sc_trace(mVcdFile, knn_set_9_2_V_read, "(port)knn_set_9_2_V_read");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, i_fu_544_p2, "i_fu_544_p2");
    sc_trace(mVcdFile, zext_ln169_fu_565_p1, "zext_ln169_fu_565_p1");
    sc_trace(mVcdFile, zext_ln169_reg_1040, "zext_ln169_reg_1040");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, i_3_fu_575_p2, "i_3_fu_575_p2");
    sc_trace(mVcdFile, i_3_reg_1048, "i_3_reg_1048");
    sc_trace(mVcdFile, icmp_ln169_fu_569_p2, "icmp_ln169_fu_569_p2");
    sc_trace(mVcdFile, sorted_labels_q0, "sorted_labels_q0");
    sc_trace(mVcdFile, sorted_labels_load_1_reg_1058, "sorted_labels_load_1_reg_1058");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, trunc_ln171_fu_586_p1, "trunc_ln171_fu_586_p1");
    sc_trace(mVcdFile, trunc_ln171_reg_1063, "trunc_ln171_reg_1063");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, j_fu_590_p2, "j_fu_590_p2");
    sc_trace(mVcdFile, j_reg_1069, "j_reg_1069");
    sc_trace(mVcdFile, icmp_ln171_fu_596_p2, "icmp_ln171_fu_596_p2");
    sc_trace(mVcdFile, freqs_0_V_4_fu_659_p3, "freqs_0_V_4_fu_659_p3");
    sc_trace(mVcdFile, freqs_0_V_5_fu_675_p3, "freqs_0_V_5_fu_675_p3");
    sc_trace(mVcdFile, freqs_0_V_6_fu_683_p3, "freqs_0_V_6_fu_683_p3");
    sc_trace(mVcdFile, select_ln879_fu_752_p3, "select_ln879_fu_752_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, select_ln879_1_fu_760_p3, "select_ln879_1_fu_760_p3");
    sc_trace(mVcdFile, select_ln879_2_fu_768_p3, "select_ln879_2_fu_768_p3");
    sc_trace(mVcdFile, local_cnt_V_1_fu_776_p3, "local_cnt_V_1_fu_776_p3");
    sc_trace(mVcdFile, select_ln183_fu_830_p3, "select_ln183_fu_830_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, icmp_ln182_fu_784_p2, "icmp_ln182_fu_784_p2");
    sc_trace(mVcdFile, i_2_fu_838_p2, "i_2_fu_838_p2");
    sc_trace(mVcdFile, sorted_distances_q0, "sorted_distances_q0");
    sc_trace(mVcdFile, sorted_distances_q1, "sorted_distances_q1");
    sc_trace(mVcdFile, sorted_labels_address0, "sorted_labels_address0");
    sc_trace(mVcdFile, sorted_labels_ce0, "sorted_labels_ce0");
    sc_trace(mVcdFile, sorted_labels_we0, "sorted_labels_we0");
    sc_trace(mVcdFile, sorted_labels_ce1, "sorted_labels_ce1");
    sc_trace(mVcdFile, sorted_labels_we1, "sorted_labels_we1");
    sc_trace(mVcdFile, sorted_labels_q1, "sorted_labels_q1");
    sc_trace(mVcdFile, grp_sort_knn_fu_461_ap_start, "grp_sort_knn_fu_461_ap_start");
    sc_trace(mVcdFile, grp_sort_knn_fu_461_ap_done, "grp_sort_knn_fu_461_ap_done");
    sc_trace(mVcdFile, grp_sort_knn_fu_461_ap_idle, "grp_sort_knn_fu_461_ap_idle");
    sc_trace(mVcdFile, grp_sort_knn_fu_461_ap_ready, "grp_sort_knn_fu_461_ap_ready");
    sc_trace(mVcdFile, grp_sort_knn_fu_461_sorted_distances_V_address0, "grp_sort_knn_fu_461_sorted_distances_V_address0");
    sc_trace(mVcdFile, grp_sort_knn_fu_461_sorted_distances_V_ce0, "grp_sort_knn_fu_461_sorted_distances_V_ce0");
    sc_trace(mVcdFile, grp_sort_knn_fu_461_sorted_distances_V_we0, "grp_sort_knn_fu_461_sorted_distances_V_we0");
    sc_trace(mVcdFile, grp_sort_knn_fu_461_sorted_distances_V_d0, "grp_sort_knn_fu_461_sorted_distances_V_d0");
    sc_trace(mVcdFile, grp_sort_knn_fu_461_sorted_distances_V_address1, "grp_sort_knn_fu_461_sorted_distances_V_address1");
    sc_trace(mVcdFile, grp_sort_knn_fu_461_sorted_distances_V_ce1, "grp_sort_knn_fu_461_sorted_distances_V_ce1");
    sc_trace(mVcdFile, grp_sort_knn_fu_461_sorted_distances_V_we1, "grp_sort_knn_fu_461_sorted_distances_V_we1");
    sc_trace(mVcdFile, grp_sort_knn_fu_461_sorted_distances_V_d1, "grp_sort_knn_fu_461_sorted_distances_V_d1");
    sc_trace(mVcdFile, grp_sort_knn_fu_461_sorted_labels_V_address0, "grp_sort_knn_fu_461_sorted_labels_V_address0");
    sc_trace(mVcdFile, grp_sort_knn_fu_461_sorted_labels_V_ce0, "grp_sort_knn_fu_461_sorted_labels_V_ce0");
    sc_trace(mVcdFile, grp_sort_knn_fu_461_sorted_labels_V_we0, "grp_sort_knn_fu_461_sorted_labels_V_we0");
    sc_trace(mVcdFile, grp_sort_knn_fu_461_sorted_labels_V_d0, "grp_sort_knn_fu_461_sorted_labels_V_d0");
    sc_trace(mVcdFile, grp_sort_knn_fu_461_sorted_labels_V_address1, "grp_sort_knn_fu_461_sorted_labels_V_address1");
    sc_trace(mVcdFile, grp_sort_knn_fu_461_sorted_labels_V_ce1, "grp_sort_knn_fu_461_sorted_labels_V_ce1");
    sc_trace(mVcdFile, grp_sort_knn_fu_461_sorted_labels_V_we1, "grp_sort_knn_fu_461_sorted_labels_V_we1");
    sc_trace(mVcdFile, grp_sort_knn_fu_461_sorted_labels_V_d1, "grp_sort_knn_fu_461_sorted_labels_V_d1");
    sc_trace(mVcdFile, ap_phi_mux_i_0_phi_fu_336_p4, "ap_phi_mux_i_0_phi_fu_336_p4");
    sc_trace(mVcdFile, i_0_reg_332, "i_0_reg_332");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, icmp_ln164_fu_538_p2, "icmp_ln164_fu_538_p2");
    sc_trace(mVcdFile, freqs_2_V_2_reg_343, "freqs_2_V_2_reg_343");
    sc_trace(mVcdFile, freqs_1_V_2_reg_353, "freqs_1_V_2_reg_353");
    sc_trace(mVcdFile, freqs_0_V_2_reg_363, "freqs_0_V_2_reg_363");
    sc_trace(mVcdFile, i3_0_reg_373, "i3_0_reg_373");
    sc_trace(mVcdFile, freqs_2_V_3_reg_385, "freqs_2_V_3_reg_385");
    sc_trace(mVcdFile, freqs_1_V_3_reg_396, "freqs_1_V_3_reg_396");
    sc_trace(mVcdFile, freqs_0_V_reg_407, "freqs_0_V_reg_407");
    sc_trace(mVcdFile, t_V_reg_418, "t_V_reg_418");
    sc_trace(mVcdFile, j_0_in_reg_430, "j_0_in_reg_430");
    sc_trace(mVcdFile, p_022_0_reg_439, "p_022_0_reg_439");
    sc_trace(mVcdFile, val_assign_reg_450, "val_assign_reg_450");
    sc_trace(mVcdFile, grp_sort_knn_fu_461_ap_start_reg, "grp_sort_knn_fu_461_ap_start_reg");
    sc_trace(mVcdFile, zext_ln172_fu_581_p1, "zext_ln172_fu_581_p1");
    sc_trace(mVcdFile, sext_ln172_fu_602_p1, "sext_ln172_fu_602_p1");
    sc_trace(mVcdFile, zext_ln544_fu_844_p1, "zext_ln544_fu_844_p1");
    sc_trace(mVcdFile, freqs_0_V_0_fu_106, "freqs_0_V_0_fu_106");
    sc_trace(mVcdFile, freqs_1_V_0_fu_110, "freqs_1_V_0_fu_110");
    sc_trace(mVcdFile, freqs_2_V_0_fu_114, "freqs_2_V_0_fu_114");
    sc_trace(mVcdFile, tmp_4_fu_607_p5, "tmp_4_fu_607_p5");
    sc_trace(mVcdFile, icmp_ln321_1_fu_631_p2, "icmp_ln321_1_fu_631_p2");
    sc_trace(mVcdFile, icmp_ln883_fu_619_p2, "icmp_ln883_fu_619_p2");
    sc_trace(mVcdFile, icmp_ln321_fu_625_p2, "icmp_ln321_fu_625_p2");
    sc_trace(mVcdFile, or_ln883_fu_645_p2, "or_ln883_fu_645_p2");
    sc_trace(mVcdFile, select_ln883_fu_651_p3, "select_ln883_fu_651_p3");
    sc_trace(mVcdFile, select_ln883_2_fu_667_p3, "select_ln883_2_fu_667_p3");
    sc_trace(mVcdFile, freqs_0_V_3_fu_637_p3, "freqs_0_V_3_fu_637_p3");
    sc_trace(mVcdFile, icmp_ln321_2_fu_702_p2, "icmp_ln321_2_fu_702_p2");
    sc_trace(mVcdFile, icmp_ln321_3_fu_715_p2, "icmp_ln321_3_fu_715_p2");
    sc_trace(mVcdFile, select_ln321_fu_707_p3, "select_ln321_fu_707_p3");
    sc_trace(mVcdFile, select_ln321_2_fu_728_p3, "select_ln321_2_fu_728_p3");
    sc_trace(mVcdFile, icmp_ln879_fu_691_p2, "icmp_ln879_fu_691_p2");
    sc_trace(mVcdFile, select_ln321_1_fu_720_p3, "select_ln321_1_fu_720_p3");
    sc_trace(mVcdFile, select_ln321_3_fu_736_p3, "select_ln321_3_fu_736_p3");
    sc_trace(mVcdFile, select_ln321_4_fu_744_p3, "select_ln321_4_fu_744_p3");
    sc_trace(mVcdFile, local_cnt_V_fu_696_p2, "local_cnt_V_fu_696_p2");
    sc_trace(mVcdFile, icmp_ln895_2_fu_790_p2, "icmp_ln895_2_fu_790_p2");
    sc_trace(mVcdFile, tmp_3_fu_808_p4, "tmp_3_fu_808_p4");
    sc_trace(mVcdFile, select_ln895_fu_796_p3, "select_ln895_fu_796_p3");
    sc_trace(mVcdFile, tmp_3_fu_808_p5, "tmp_3_fu_808_p5");
    sc_trace(mVcdFile, icmp_ln895_fu_820_p2, "icmp_ln895_fu_820_p2");
    sc_trace(mVcdFile, max_idx_V_fu_826_p1, "max_idx_V_fu_826_p1");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

knn_vote::~knn_vote() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete sorted_distances_U;
    delete sorted_labels_U;
    delete grp_sort_knn_fu_461;
    delete dut_mux_32_4_1_1_U52;
    delete dut_mux_32_4_1_1_U53;
}

void knn_vote::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv4_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
            ap_return_preg = sorted_labels_q0.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln164_fu_538_p2.read()))) {
        freqs_0_V_2_reg_363 = freqs_0_V_0_fu_106.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(icmp_ln171_fu_596_p2.read(), ap_const_lv1_1))) {
        freqs_0_V_2_reg_363 = freqs_0_V_6_fu_683_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        freqs_0_V_reg_407 = select_ln879_2_fu_768_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        freqs_0_V_reg_407 = freqs_0_V_2_reg_363.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln164_fu_538_p2.read()))) {
        freqs_1_V_2_reg_353 = freqs_1_V_0_fu_110.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(icmp_ln171_fu_596_p2.read(), ap_const_lv1_1))) {
        freqs_1_V_2_reg_353 = freqs_0_V_5_fu_675_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        freqs_1_V_3_reg_396 = select_ln879_1_fu_760_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        freqs_1_V_3_reg_396 = freqs_1_V_2_reg_353.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln164_fu_538_p2.read()))) {
        freqs_2_V_2_reg_343 = freqs_2_V_0_fu_114.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(icmp_ln171_fu_596_p2.read(), ap_const_lv1_1))) {
        freqs_2_V_2_reg_343 = freqs_0_V_4_fu_659_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        freqs_2_V_3_reg_385 = select_ln879_fu_752_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        freqs_2_V_3_reg_385 = freqs_2_V_2_reg_343.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_sort_knn_fu_461_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            grp_sort_knn_fu_461_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_sort_knn_fu_461_ap_ready.read())) {
            grp_sort_knn_fu_461_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln164_fu_538_p2.read()))) {
        i3_0_reg_373 = ap_const_lv2_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(icmp_ln171_fu_596_p2.read(), ap_const_lv1_1))) {
        i3_0_reg_373 = i_3_reg_1048.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln164_fu_538_p2.read()))) {
        i_0_reg_332 = i_fu_544_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(grp_sort_knn_fu_461_ap_done.read(), ap_const_logic_1))) {
        i_0_reg_332 = ap_const_lv2_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        j_0_in_reg_430 = j_reg_1069.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        j_0_in_reg_430 = zext_ln169_reg_1040.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln169_fu_569_p2.read(), ap_const_lv1_1))) {
        p_022_0_reg_439 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln182_fu_784_p2.read()))) {
        p_022_0_reg_439 = select_ln183_fu_830_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        t_V_reg_418 = local_cnt_V_1_fu_776_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        t_V_reg_418 = ap_const_lv4_1;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln169_fu_569_p2.read(), ap_const_lv1_1))) {
        val_assign_reg_450 = ap_const_lv2_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln182_fu_784_p2.read()))) {
        val_assign_reg_450 = i_2_fu_838_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        i_3_reg_1048 = i_3_fu_575_p2.read();
        zext_ln169_reg_1040 = zext_ln169_fu_565_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        j_reg_1069 = j_fu_590_p2.read();
        trunc_ln171_reg_1063 = trunc_ln171_fu_586_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        sorted_labels_load_1_reg_1058 = sorted_labels_q0.read();
    }
}

void knn_vote::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void knn_vote::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void knn_vote::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void knn_vote::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void knn_vote::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void knn_vote::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void knn_vote::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void knn_vote::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void knn_vote::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void knn_vote::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void knn_vote::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void knn_vote::thread_ap_phi_mux_i_0_phi_fu_336_p4() {
    ap_phi_mux_i_0_phi_fu_336_p4 = i_0_reg_332.read();
}

void knn_vote::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void knn_vote::thread_ap_return() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        ap_return = sorted_labels_q0.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void knn_vote::thread_freqs_0_V_0_fu_106() {
    freqs_0_V_0_fu_106 = ap_const_lv4_F;
}

void knn_vote::thread_freqs_0_V_3_fu_637_p3() {
    freqs_0_V_3_fu_637_p3 = (!icmp_ln321_1_fu_631_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln321_1_fu_631_p2.read()[0].to_bool())? t_V_reg_418.read(): freqs_0_V_reg_407.read());
}

void knn_vote::thread_freqs_0_V_4_fu_659_p3() {
    freqs_0_V_4_fu_659_p3 = (!or_ln883_fu_645_p2.read()[0].is_01())? sc_lv<4>(): ((or_ln883_fu_645_p2.read()[0].to_bool())? freqs_2_V_3_reg_385.read(): select_ln883_fu_651_p3.read());
}

void knn_vote::thread_freqs_0_V_5_fu_675_p3() {
    freqs_0_V_5_fu_675_p3 = (!or_ln883_fu_645_p2.read()[0].is_01())? sc_lv<4>(): ((or_ln883_fu_645_p2.read()[0].to_bool())? freqs_1_V_3_reg_396.read(): select_ln883_2_fu_667_p3.read());
}

void knn_vote::thread_freqs_0_V_6_fu_683_p3() {
    freqs_0_V_6_fu_683_p3 = (!icmp_ln883_fu_619_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln883_fu_619_p2.read()[0].to_bool())? freqs_0_V_reg_407.read(): freqs_0_V_3_fu_637_p3.read());
}

void knn_vote::thread_freqs_1_V_0_fu_110() {
    freqs_1_V_0_fu_110 = ap_const_lv4_F;
}

void knn_vote::thread_freqs_2_V_0_fu_114() {
    freqs_2_V_0_fu_114 = ap_const_lv4_F;
}

void knn_vote::thread_grp_sort_knn_fu_461_ap_start() {
    grp_sort_knn_fu_461_ap_start = grp_sort_knn_fu_461_ap_start_reg.read();
}

void knn_vote::thread_i_2_fu_838_p2() {
    i_2_fu_838_p2 = (!ap_const_lv2_1.is_01() || !val_assign_reg_450.read().is_01())? sc_lv<2>(): (sc_biguint<2>(ap_const_lv2_1) + sc_biguint<2>(val_assign_reg_450.read()));
}

void knn_vote::thread_i_3_fu_575_p2() {
    i_3_fu_575_p2 = (!i3_0_reg_373.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i3_0_reg_373.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void knn_vote::thread_i_fu_544_p2() {
    i_fu_544_p2 = (!i_0_reg_332.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i_0_reg_332.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void knn_vote::thread_icmp_ln164_fu_538_p2() {
    icmp_ln164_fu_538_p2 = (!i_0_reg_332.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_332.read() == ap_const_lv2_3);
}

void knn_vote::thread_icmp_ln169_fu_569_p2() {
    icmp_ln169_fu_569_p2 = (!i3_0_reg_373.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(i3_0_reg_373.read() == ap_const_lv2_3);
}

void knn_vote::thread_icmp_ln171_fu_596_p2() {
    icmp_ln171_fu_596_p2 = (!j_0_in_reg_430.read().is_01() || !ap_const_lv32_2.is_01())? sc_lv<1>(): sc_lv<1>(j_0_in_reg_430.read() == ap_const_lv32_2);
}

void knn_vote::thread_icmp_ln182_fu_784_p2() {
    icmp_ln182_fu_784_p2 = (!val_assign_reg_450.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(val_assign_reg_450.read() == ap_const_lv2_3);
}

void knn_vote::thread_icmp_ln321_1_fu_631_p2() {
    icmp_ln321_1_fu_631_p2 = (!i3_0_reg_373.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(i3_0_reg_373.read() == ap_const_lv2_0);
}

void knn_vote::thread_icmp_ln321_2_fu_702_p2() {
    icmp_ln321_2_fu_702_p2 = (!trunc_ln171_reg_1063.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln171_reg_1063.read() == ap_const_lv2_0);
}

void knn_vote::thread_icmp_ln321_3_fu_715_p2() {
    icmp_ln321_3_fu_715_p2 = (!trunc_ln171_reg_1063.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln171_reg_1063.read() == ap_const_lv2_3);
}

void knn_vote::thread_icmp_ln321_fu_625_p2() {
    icmp_ln321_fu_625_p2 = (!i3_0_reg_373.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(i3_0_reg_373.read() == ap_const_lv2_1);
}

void knn_vote::thread_icmp_ln879_fu_691_p2() {
    icmp_ln879_fu_691_p2 = (!sorted_labels_load_1_reg_1058.read().is_01() || !sorted_labels_q0.read().is_01())? sc_lv<1>(): sc_lv<1>(sorted_labels_load_1_reg_1058.read() == sorted_labels_q0.read());
}

void knn_vote::thread_icmp_ln883_fu_619_p2() {
    icmp_ln883_fu_619_p2 = (!tmp_4_fu_607_p5.read().is_01() || !ap_const_lv4_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_4_fu_607_p5.read() == ap_const_lv4_0);
}

void knn_vote::thread_icmp_ln895_2_fu_790_p2() {
    icmp_ln895_2_fu_790_p2 = (!val_assign_reg_450.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(val_assign_reg_450.read() == ap_const_lv2_1);
}

void knn_vote::thread_icmp_ln895_fu_820_p2() {
    icmp_ln895_fu_820_p2 = (!select_ln895_fu_796_p3.read().is_01() || !tmp_3_fu_808_p5.read().is_01())? sc_lv<1>(): (sc_biguint<4>(select_ln895_fu_796_p3.read()) > sc_biguint<4>(tmp_3_fu_808_p5.read()));
}

void knn_vote::thread_j_fu_590_p2() {
    j_fu_590_p2 = (!ap_const_lv32_1.is_01() || !j_0_in_reg_430.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1) + sc_biguint<32>(j_0_in_reg_430.read()));
}

void knn_vote::thread_local_cnt_V_1_fu_776_p3() {
    local_cnt_V_1_fu_776_p3 = (!icmp_ln879_fu_691_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln879_fu_691_p2.read()[0].to_bool())? local_cnt_V_fu_696_p2.read(): t_V_reg_418.read());
}

void knn_vote::thread_local_cnt_V_fu_696_p2() {
    local_cnt_V_fu_696_p2 = (!t_V_reg_418.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(t_V_reg_418.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void knn_vote::thread_max_idx_V_fu_826_p1() {
    max_idx_V_fu_826_p1 = esl_zext<4,2>(val_assign_reg_450.read());
}

void knn_vote::thread_or_ln883_fu_645_p2() {
    or_ln883_fu_645_p2 = (icmp_ln883_fu_619_p2.read() | icmp_ln321_1_fu_631_p2.read());
}

void knn_vote::thread_select_ln183_fu_830_p3() {
    select_ln183_fu_830_p3 = (!icmp_ln895_fu_820_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln895_fu_820_p2.read()[0].to_bool())? max_idx_V_fu_826_p1.read(): p_022_0_reg_439.read());
}

void knn_vote::thread_select_ln321_1_fu_720_p3() {
    select_ln321_1_fu_720_p3 = (!icmp_ln321_3_fu_715_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln321_3_fu_715_p2.read()[0].to_bool())? freqs_2_V_3_reg_385.read(): select_ln321_fu_707_p3.read());
}

void knn_vote::thread_select_ln321_2_fu_728_p3() {
    select_ln321_2_fu_728_p3 = (!icmp_ln321_2_fu_702_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln321_2_fu_702_p2.read()[0].to_bool())? ap_const_lv4_0: freqs_1_V_3_reg_396.read());
}

void knn_vote::thread_select_ln321_3_fu_736_p3() {
    select_ln321_3_fu_736_p3 = (!icmp_ln321_3_fu_715_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln321_3_fu_715_p2.read()[0].to_bool())? freqs_1_V_3_reg_396.read(): select_ln321_2_fu_728_p3.read());
}

void knn_vote::thread_select_ln321_4_fu_744_p3() {
    select_ln321_4_fu_744_p3 = (!icmp_ln321_3_fu_715_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln321_3_fu_715_p2.read()[0].to_bool())? ap_const_lv4_0: freqs_0_V_reg_407.read());
}

void knn_vote::thread_select_ln321_fu_707_p3() {
    select_ln321_fu_707_p3 = (!icmp_ln321_2_fu_702_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln321_2_fu_702_p2.read()[0].to_bool())? freqs_2_V_3_reg_385.read(): ap_const_lv4_0);
}

void knn_vote::thread_select_ln879_1_fu_760_p3() {
    select_ln879_1_fu_760_p3 = (!icmp_ln879_fu_691_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln879_fu_691_p2.read()[0].to_bool())? select_ln321_3_fu_736_p3.read(): freqs_1_V_3_reg_396.read());
}

void knn_vote::thread_select_ln879_2_fu_768_p3() {
    select_ln879_2_fu_768_p3 = (!icmp_ln879_fu_691_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln879_fu_691_p2.read()[0].to_bool())? select_ln321_4_fu_744_p3.read(): freqs_0_V_reg_407.read());
}

void knn_vote::thread_select_ln879_fu_752_p3() {
    select_ln879_fu_752_p3 = (!icmp_ln879_fu_691_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln879_fu_691_p2.read()[0].to_bool())? select_ln321_1_fu_720_p3.read(): freqs_2_V_3_reg_385.read());
}

void knn_vote::thread_select_ln883_2_fu_667_p3() {
    select_ln883_2_fu_667_p3 = (!icmp_ln321_fu_625_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln321_fu_625_p2.read()[0].to_bool())? t_V_reg_418.read(): freqs_1_V_3_reg_396.read());
}

void knn_vote::thread_select_ln883_fu_651_p3() {
    select_ln883_fu_651_p3 = (!icmp_ln321_fu_625_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln321_fu_625_p2.read()[0].to_bool())? freqs_2_V_3_reg_385.read(): t_V_reg_418.read());
}

void knn_vote::thread_select_ln895_fu_796_p3() {
    select_ln895_fu_796_p3 = (!icmp_ln895_2_fu_790_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln895_2_fu_790_p2.read()[0].to_bool())? freqs_1_V_2_reg_353.read(): freqs_2_V_2_reg_343.read());
}

void knn_vote::thread_sext_ln172_fu_602_p1() {
    sext_ln172_fu_602_p1 = esl_sext<64,32>(j_fu_590_p2.read());
}

void knn_vote::thread_sorted_labels_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        sorted_labels_address0 =  (sc_lv<5>) (zext_ln544_fu_844_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        sorted_labels_address0 =  (sc_lv<5>) (sext_ln172_fu_602_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        sorted_labels_address0 =  (sc_lv<5>) (zext_ln172_fu_581_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        sorted_labels_address0 = grp_sort_knn_fu_461_sorted_labels_V_address0.read();
    } else {
        sorted_labels_address0 = "XXXXX";
    }
}

void knn_vote::thread_sorted_labels_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        sorted_labels_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        sorted_labels_ce0 = grp_sort_knn_fu_461_sorted_labels_V_ce0.read();
    } else {
        sorted_labels_ce0 = ap_const_logic_0;
    }
}

void knn_vote::thread_sorted_labels_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        sorted_labels_ce1 = grp_sort_knn_fu_461_sorted_labels_V_ce1.read();
    } else {
        sorted_labels_ce1 = ap_const_logic_0;
    }
}

void knn_vote::thread_sorted_labels_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        sorted_labels_we0 = grp_sort_knn_fu_461_sorted_labels_V_we0.read();
    } else {
        sorted_labels_we0 = ap_const_logic_0;
    }
}

void knn_vote::thread_sorted_labels_we1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        sorted_labels_we1 = grp_sort_knn_fu_461_sorted_labels_V_we1.read();
    } else {
        sorted_labels_we1 = ap_const_logic_0;
    }
}

void knn_vote::thread_tmp_3_fu_808_p4() {
    tmp_3_fu_808_p4 = p_022_0_reg_439.read().range(2-1, 0);
}

void knn_vote::thread_trunc_ln171_fu_586_p1() {
    trunc_ln171_fu_586_p1 = j_0_in_reg_430.read().range(2-1, 0);
}

void knn_vote::thread_zext_ln169_fu_565_p1() {
    zext_ln169_fu_565_p1 = esl_zext<32,2>(i3_0_reg_373.read());
}

void knn_vote::thread_zext_ln172_fu_581_p1() {
    zext_ln172_fu_581_p1 = esl_zext<64,2>(i3_0_reg_373.read());
}

void knn_vote::thread_zext_ln544_fu_844_p1() {
    zext_ln544_fu_844_p1 = esl_zext<64,4>(p_022_0_reg_439.read());
}

void knn_vote::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(grp_sort_knn_fu_461_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln164_fu_538_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln169_fu_569_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(icmp_ln171_fu_596_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln182_fu_784_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<9>) ("XXXXXXXXX");
            break;
    }
}

}

