// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "digitrec.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic digitrec::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic digitrec::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<11> digitrec::ap_ST_fsm_state1 = "1";
const sc_lv<11> digitrec::ap_ST_fsm_state2 = "10";
const sc_lv<11> digitrec::ap_ST_fsm_state3 = "100";
const sc_lv<11> digitrec::ap_ST_fsm_state4 = "1000";
const sc_lv<11> digitrec::ap_ST_fsm_state5 = "10000";
const sc_lv<11> digitrec::ap_ST_fsm_state6 = "100000";
const sc_lv<11> digitrec::ap_ST_fsm_state7 = "1000000";
const sc_lv<11> digitrec::ap_ST_fsm_state8 = "10000000";
const sc_lv<11> digitrec::ap_ST_fsm_state9 = "100000000";
const sc_lv<11> digitrec::ap_ST_fsm_state10 = "1000000000";
const sc_lv<11> digitrec::ap_ST_fsm_state11 = "10000000000";
const sc_lv<32> digitrec::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> digitrec::ap_const_lv32_1 = "1";
const sc_lv<1> digitrec::ap_const_lv1_0 = "0";
const sc_lv<32> digitrec::ap_const_lv32_2 = "10";
const sc_lv<32> digitrec::ap_const_lv32_3 = "11";
const sc_lv<32> digitrec::ap_const_lv32_4 = "100";
const sc_lv<32> digitrec::ap_const_lv32_5 = "101";
const sc_lv<32> digitrec::ap_const_lv32_6 = "110";
const sc_lv<32> digitrec::ap_const_lv32_7 = "111";
const sc_lv<1> digitrec::ap_const_lv1_1 = "1";
const sc_lv<32> digitrec::ap_const_lv32_8 = "1000";
const sc_lv<4> digitrec::ap_const_lv4_0 = "0000";
const sc_lv<2> digitrec::ap_const_lv2_0 = "00";
const sc_lv<11> digitrec::ap_const_lv11_0 = "00000000000";
const sc_lv<32> digitrec::ap_const_lv32_9 = "1001";
const sc_lv<15> digitrec::ap_const_lv15_0 = "000000000000000";
const sc_lv<6> digitrec::ap_const_lv6_0 = "000000";
const sc_lv<2> digitrec::ap_const_lv2_1 = "1";
const sc_lv<32> digitrec::ap_const_lv32_A = "1010";
const sc_lv<6> digitrec::ap_const_lv6_32 = "110010";
const sc_lv<4> digitrec::ap_const_lv4_A = "1010";
const sc_lv<4> digitrec::ap_const_lv4_1 = "1";
const sc_lv<2> digitrec::ap_const_lv2_3 = "11";
const sc_lv<11> digitrec::ap_const_lv11_708 = "11100001000";
const sc_lv<11> digitrec::ap_const_lv11_1 = "1";
const sc_lv<15> digitrec::ap_const_lv15_708 = "11100001000";
const sc_lv<6> digitrec::ap_const_lv6_31 = "110001";
const sc_lv<6> digitrec::ap_const_lv6_1 = "1";
const bool digitrec::ap_const_boolean_1 = true;

digitrec::digitrec(sc_module_name name) : sc_module(name), mVcdFile(0) {
    training_data_V_U = new digitrec_trainingdEe("training_data_V_U");
    training_data_V_U->clk(ap_clk);
    training_data_V_U->reset(ap_rst);
    training_data_V_U->address0(training_data_V_address0);
    training_data_V_U->ce0(training_data_V_ce0);
    training_data_V_U->q0(training_data_V_q0);
    knn_set_V_U = new digitrec_knn_set_V("knn_set_V_U");
    knn_set_V_U->clk(ap_clk);
    knn_set_V_U->reset(ap_rst);
    knn_set_V_U->address0(knn_set_V_address0);
    knn_set_V_U->ce0(knn_set_V_ce0);
    knn_set_V_U->we0(knn_set_V_we0);
    knn_set_V_U->d0(ap_var_for_const0);
    knn_set_V_U->q0(knn_set_V_q0);
    knn_set_V_U->address1(knn_set_V_address1);
    knn_set_V_U->ce1(knn_set_V_ce1);
    knn_set_V_U->we1(knn_set_V_we1);
    knn_set_V_U->d1(p_053_0_i_reg_189);
    knn_set_V_U->q1(knn_set_V_q1);
    grp_knn_vote_fu_237 = new knn_vote("grp_knn_vote_fu_237");
    grp_knn_vote_fu_237->ap_clk(ap_clk);
    grp_knn_vote_fu_237->ap_rst(ap_rst);
    grp_knn_vote_fu_237->ap_start(grp_knn_vote_fu_237_ap_start);
    grp_knn_vote_fu_237->ap_done(grp_knn_vote_fu_237_ap_done);
    grp_knn_vote_fu_237->ap_idle(grp_knn_vote_fu_237_ap_idle);
    grp_knn_vote_fu_237->ap_ready(grp_knn_vote_fu_237_ap_ready);
    grp_knn_vote_fu_237->knn_set_V_address0(grp_knn_vote_fu_237_knn_set_V_address0);
    grp_knn_vote_fu_237->knn_set_V_ce0(grp_knn_vote_fu_237_knn_set_V_ce0);
    grp_knn_vote_fu_237->knn_set_V_q0(knn_set_V_q0);
    grp_knn_vote_fu_237->ap_return(grp_knn_vote_fu_237_ap_return);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln321_fu_288_p2);
    sensitive << ( sub_ln321_reg_493 );
    sensitive << ( zext_ln321_2_fu_284_p1 );

    SC_METHOD(thread_add_ln59_fu_314_p2);
    sensitive << ( phi_mul_reg_178 );

    SC_METHOD(thread_add_ln61_fu_332_p2);
    sensitive << ( zext_ln59_reg_514 );
    sensitive << ( phi_mul_reg_178 );

    SC_METHOD(thread_add_ln895_1_fu_412_p2);
    sensitive << ( sub_ln895_reg_537 );
    sensitive << ( zext_ln895_1_fu_408_p1 );

    SC_METHOD(thread_add_ln895_2_fu_426_p2);
    sensitive << ( sub_ln895_reg_537 );
    sensitive << ( zext_ln895_2_fu_422_p1 );

    SC_METHOD(thread_add_ln895_fu_440_p2);
    sensitive << ( sub_ln895_reg_537 );
    sensitive << ( zext_ln895_fu_436_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( grp_knn_vote_fu_237_ap_done );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( grp_knn_vote_fu_237_ap_done );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_ap_return);
    sensitive << ( grp_knn_vote_fu_237_ap_done );
    sensitive << ( grp_knn_vote_fu_237_ap_return );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_return_preg );

    SC_METHOD(thread_dist_V_fu_396_p2);
    sensitive << ( p_053_0_i_reg_189 );
    sensitive << ( zext_ln700_fu_392_p1 );

    SC_METHOD(thread_grp_knn_vote_fu_237_ap_start);
    sensitive << ( grp_knn_vote_fu_237_ap_start_reg );

    SC_METHOD(thread_i_3_fu_304_p2);
    sensitive << ( i4_0_reg_155 );

    SC_METHOD(thread_i_4_fu_379_p2);
    sensitive << ( bvh_d_index_reg_202 );

    SC_METHOD(thread_i_5_fu_468_p2);
    sensitive << ( val_assign_reg_225 );

    SC_METHOD(thread_i_fu_248_p2);
    sensitive << ( i_0_reg_133 );

    SC_METHOD(thread_icmp_ln51_fu_242_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_133 );

    SC_METHOD(thread_icmp_ln52_fu_272_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( k_0_reg_144 );

    SC_METHOD(thread_icmp_ln57_fu_298_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( i4_0_reg_155 );

    SC_METHOD(thread_icmp_ln59_fu_320_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( j_0_reg_166 );

    SC_METHOD(thread_icmp_ln895_2_fu_450_p2);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( knn_set_V_q0 );
    sensitive << ( knn_set_V_q1 );

    SC_METHOD(thread_icmp_ln895_fu_474_p2);
    sensitive << ( knn_set_V_q0 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( p_053_0_i_reg_189 );

    SC_METHOD(thread_icmp_ln89_fu_373_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( bvh_d_index_reg_202 );

    SC_METHOD(thread_icmp_ln95_fu_402_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( val_assign_reg_225 );

    SC_METHOD(thread_j_fu_326_p2);
    sensitive << ( j_0_reg_166 );

    SC_METHOD(thread_k_fu_278_p2);
    sensitive << ( k_0_reg_144 );

    SC_METHOD(thread_knn_set_V_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln95_fu_402_p2 );
    sensitive << ( grp_knn_vote_fu_237_knn_set_V_address0 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( sext_ln321_fu_293_p1 );
    sensitive << ( sext_ln895_1_fu_417_p1 );
    sensitive << ( sext_ln895_fu_445_p1 );

    SC_METHOD(thread_knn_set_V_address1);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( knn_set_V_addr_1_reg_575 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( sext_ln895_2_fu_431_p1 );

    SC_METHOD(thread_knn_set_V_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln95_fu_402_p2 );
    sensitive << ( grp_knn_vote_fu_237_knn_set_V_ce0 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_knn_set_V_ce1);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_knn_set_V_we0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln52_fu_272_p2 );

    SC_METHOD(thread_knn_set_V_we1);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( icmp_ln895_fu_474_p2 );

    SC_METHOD(thread_max_idx_V_fu_456_p1);
    sensitive << ( val_assign_reg_225 );

    SC_METHOD(thread_p_Result_s_fu_385_p3);
    sensitive << ( ret_V_reg_544 );
    sensitive << ( zext_ln89_fu_369_p1 );

    SC_METHOD(thread_ret_V_fu_364_p2);
    sensitive << ( input_V );
    sensitive << ( zext_ln61_2_fu_360_p1 );

    SC_METHOD(thread_select_ln96_fu_460_p3);
    sensitive << ( p_032_0_i_reg_213 );
    sensitive << ( icmp_ln895_2_fu_450_p2 );
    sensitive << ( max_idx_V_fu_456_p1 );

    SC_METHOD(thread_sext_ln321_fu_293_p1);
    sensitive << ( add_ln321_fu_288_p2 );

    SC_METHOD(thread_sext_ln895_1_fu_417_p1);
    sensitive << ( add_ln895_1_fu_412_p2 );

    SC_METHOD(thread_sext_ln895_2_fu_431_p1);
    sensitive << ( add_ln895_2_fu_426_p2 );

    SC_METHOD(thread_sext_ln895_fu_445_p1);
    sensitive << ( add_ln895_fu_440_p2 );

    SC_METHOD(thread_sub_ln321_fu_266_p2);
    sensitive << ( tmp_3_fu_258_p3 );
    sensitive << ( zext_ln321_fu_254_p1 );

    SC_METHOD(thread_sub_ln895_fu_354_p2);
    sensitive << ( tmp_4_fu_346_p3 );
    sensitive << ( zext_ln61_fu_342_p1 );

    SC_METHOD(thread_tmp_3_fu_258_p3);
    sensitive << ( i_0_reg_133 );

    SC_METHOD(thread_tmp_4_fu_346_p3);
    sensitive << ( j_0_reg_166 );

    SC_METHOD(thread_training_data_V_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( zext_ln61_1_fu_337_p1 );

    SC_METHOD(thread_training_data_V_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_zext_ln321_2_fu_284_p1);
    sensitive << ( k_0_reg_144 );

    SC_METHOD(thread_zext_ln321_fu_254_p1);
    sensitive << ( i_0_reg_133 );

    SC_METHOD(thread_zext_ln59_fu_310_p1);
    sensitive << ( i4_0_reg_155 );

    SC_METHOD(thread_zext_ln61_1_fu_337_p1);
    sensitive << ( add_ln61_fu_332_p2 );

    SC_METHOD(thread_zext_ln61_2_fu_360_p1);
    sensitive << ( training_data_V_q0 );

    SC_METHOD(thread_zext_ln61_fu_342_p1);
    sensitive << ( j_0_reg_166 );

    SC_METHOD(thread_zext_ln700_fu_392_p1);
    sensitive << ( p_Result_s_fu_385_p3 );

    SC_METHOD(thread_zext_ln895_1_fu_408_p1);
    sensitive << ( val_assign_reg_225 );

    SC_METHOD(thread_zext_ln895_2_fu_422_p1);
    sensitive << ( p_032_0_i_reg_213 );

    SC_METHOD(thread_zext_ln895_fu_436_p1);
    sensitive << ( p_032_0_i_reg_213 );

    SC_METHOD(thread_zext_ln89_fu_369_p1);
    sensitive << ( bvh_d_index_reg_202 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln51_fu_242_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln57_fu_298_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln59_fu_320_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln89_fu_373_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln95_fu_402_p2 );
    sensitive << ( grp_knn_vote_fu_237_ap_done );
    sensitive << ( icmp_ln52_fu_272_p2 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "00000000001";
    grp_knn_vote_fu_237_ap_start_reg = SC_LOGIC_0;
    ap_return_preg = "0000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "digitrec_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_V, "(port)input_V");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, training_data_V_address0, "training_data_V_address0");
    sc_trace(mVcdFile, training_data_V_ce0, "training_data_V_ce0");
    sc_trace(mVcdFile, training_data_V_q0, "training_data_V_q0");
    sc_trace(mVcdFile, i_fu_248_p2, "i_fu_248_p2");
    sc_trace(mVcdFile, i_reg_488, "i_reg_488");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, sub_ln321_fu_266_p2, "sub_ln321_fu_266_p2");
    sc_trace(mVcdFile, sub_ln321_reg_493, "sub_ln321_reg_493");
    sc_trace(mVcdFile, icmp_ln51_fu_242_p2, "icmp_ln51_fu_242_p2");
    sc_trace(mVcdFile, k_fu_278_p2, "k_fu_278_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, i_3_fu_304_p2, "i_3_fu_304_p2");
    sc_trace(mVcdFile, i_3_reg_509, "i_3_reg_509");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, zext_ln59_fu_310_p1, "zext_ln59_fu_310_p1");
    sc_trace(mVcdFile, zext_ln59_reg_514, "zext_ln59_reg_514");
    sc_trace(mVcdFile, icmp_ln57_fu_298_p2, "icmp_ln57_fu_298_p2");
    sc_trace(mVcdFile, add_ln59_fu_314_p2, "add_ln59_fu_314_p2");
    sc_trace(mVcdFile, add_ln59_reg_519, "add_ln59_reg_519");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, j_fu_326_p2, "j_fu_326_p2");
    sc_trace(mVcdFile, j_reg_527, "j_reg_527");
    sc_trace(mVcdFile, icmp_ln59_fu_320_p2, "icmp_ln59_fu_320_p2");
    sc_trace(mVcdFile, sub_ln895_fu_354_p2, "sub_ln895_fu_354_p2");
    sc_trace(mVcdFile, sub_ln895_reg_537, "sub_ln895_reg_537");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, ret_V_fu_364_p2, "ret_V_fu_364_p2");
    sc_trace(mVcdFile, ret_V_reg_544, "ret_V_reg_544");
    sc_trace(mVcdFile, i_4_fu_379_p2, "i_4_fu_379_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, dist_V_fu_396_p2, "dist_V_fu_396_p2");
    sc_trace(mVcdFile, icmp_ln89_fu_373_p2, "icmp_ln89_fu_373_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, icmp_ln95_fu_402_p2, "icmp_ln95_fu_402_p2");
    sc_trace(mVcdFile, knn_set_V_addr_1_reg_575, "knn_set_V_addr_1_reg_575");
    sc_trace(mVcdFile, select_ln96_fu_460_p3, "select_ln96_fu_460_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, i_5_fu_468_p2, "i_5_fu_468_p2");
    sc_trace(mVcdFile, knn_set_V_address0, "knn_set_V_address0");
    sc_trace(mVcdFile, knn_set_V_ce0, "knn_set_V_ce0");
    sc_trace(mVcdFile, knn_set_V_we0, "knn_set_V_we0");
    sc_trace(mVcdFile, knn_set_V_q0, "knn_set_V_q0");
    sc_trace(mVcdFile, knn_set_V_address1, "knn_set_V_address1");
    sc_trace(mVcdFile, knn_set_V_ce1, "knn_set_V_ce1");
    sc_trace(mVcdFile, knn_set_V_we1, "knn_set_V_we1");
    sc_trace(mVcdFile, knn_set_V_q1, "knn_set_V_q1");
    sc_trace(mVcdFile, grp_knn_vote_fu_237_ap_start, "grp_knn_vote_fu_237_ap_start");
    sc_trace(mVcdFile, grp_knn_vote_fu_237_ap_done, "grp_knn_vote_fu_237_ap_done");
    sc_trace(mVcdFile, grp_knn_vote_fu_237_ap_idle, "grp_knn_vote_fu_237_ap_idle");
    sc_trace(mVcdFile, grp_knn_vote_fu_237_ap_ready, "grp_knn_vote_fu_237_ap_ready");
    sc_trace(mVcdFile, grp_knn_vote_fu_237_knn_set_V_address0, "grp_knn_vote_fu_237_knn_set_V_address0");
    sc_trace(mVcdFile, grp_knn_vote_fu_237_knn_set_V_ce0, "grp_knn_vote_fu_237_knn_set_V_ce0");
    sc_trace(mVcdFile, grp_knn_vote_fu_237_ap_return, "grp_knn_vote_fu_237_ap_return");
    sc_trace(mVcdFile, i_0_reg_133, "i_0_reg_133");
    sc_trace(mVcdFile, icmp_ln52_fu_272_p2, "icmp_ln52_fu_272_p2");
    sc_trace(mVcdFile, k_0_reg_144, "k_0_reg_144");
    sc_trace(mVcdFile, i4_0_reg_155, "i4_0_reg_155");
    sc_trace(mVcdFile, j_0_reg_166, "j_0_reg_166");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, phi_mul_reg_178, "phi_mul_reg_178");
    sc_trace(mVcdFile, p_053_0_i_reg_189, "p_053_0_i_reg_189");
    sc_trace(mVcdFile, bvh_d_index_reg_202, "bvh_d_index_reg_202");
    sc_trace(mVcdFile, p_032_0_i_reg_213, "p_032_0_i_reg_213");
    sc_trace(mVcdFile, val_assign_reg_225, "val_assign_reg_225");
    sc_trace(mVcdFile, grp_knn_vote_fu_237_ap_start_reg, "grp_knn_vote_fu_237_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, sext_ln321_fu_293_p1, "sext_ln321_fu_293_p1");
    sc_trace(mVcdFile, zext_ln61_1_fu_337_p1, "zext_ln61_1_fu_337_p1");
    sc_trace(mVcdFile, sext_ln895_1_fu_417_p1, "sext_ln895_1_fu_417_p1");
    sc_trace(mVcdFile, sext_ln895_2_fu_431_p1, "sext_ln895_2_fu_431_p1");
    sc_trace(mVcdFile, sext_ln895_fu_445_p1, "sext_ln895_fu_445_p1");
    sc_trace(mVcdFile, icmp_ln895_fu_474_p2, "icmp_ln895_fu_474_p2");
    sc_trace(mVcdFile, tmp_3_fu_258_p3, "tmp_3_fu_258_p3");
    sc_trace(mVcdFile, zext_ln321_fu_254_p1, "zext_ln321_fu_254_p1");
    sc_trace(mVcdFile, zext_ln321_2_fu_284_p1, "zext_ln321_2_fu_284_p1");
    sc_trace(mVcdFile, add_ln321_fu_288_p2, "add_ln321_fu_288_p2");
    sc_trace(mVcdFile, add_ln61_fu_332_p2, "add_ln61_fu_332_p2");
    sc_trace(mVcdFile, tmp_4_fu_346_p3, "tmp_4_fu_346_p3");
    sc_trace(mVcdFile, zext_ln61_fu_342_p1, "zext_ln61_fu_342_p1");
    sc_trace(mVcdFile, zext_ln61_2_fu_360_p1, "zext_ln61_2_fu_360_p1");
    sc_trace(mVcdFile, zext_ln89_fu_369_p1, "zext_ln89_fu_369_p1");
    sc_trace(mVcdFile, p_Result_s_fu_385_p3, "p_Result_s_fu_385_p3");
    sc_trace(mVcdFile, zext_ln700_fu_392_p1, "zext_ln700_fu_392_p1");
    sc_trace(mVcdFile, zext_ln895_1_fu_408_p1, "zext_ln895_1_fu_408_p1");
    sc_trace(mVcdFile, add_ln895_1_fu_412_p2, "add_ln895_1_fu_412_p2");
    sc_trace(mVcdFile, zext_ln895_2_fu_422_p1, "zext_ln895_2_fu_422_p1");
    sc_trace(mVcdFile, add_ln895_2_fu_426_p2, "add_ln895_2_fu_426_p2");
    sc_trace(mVcdFile, zext_ln895_fu_436_p1, "zext_ln895_fu_436_p1");
    sc_trace(mVcdFile, add_ln895_fu_440_p2, "add_ln895_fu_440_p2");
    sc_trace(mVcdFile, icmp_ln895_2_fu_450_p2, "icmp_ln895_2_fu_450_p2");
    sc_trace(mVcdFile, max_idx_V_fu_456_p1, "max_idx_V_fu_456_p1");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

digitrec::~digitrec() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete training_data_V_U;
    delete knn_set_V_U;
    delete grp_knn_vote_fu_237;
}

void digitrec::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv6_32;
}

void digitrec::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv4_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
             esl_seteq<1,1,1>(grp_knn_vote_fu_237_ap_done.read(), ap_const_logic_1))) {
            ap_return_preg = grp_knn_vote_fu_237_ap_return.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln89_fu_373_p2.read()))) {
        bvh_d_index_reg_202 = i_4_fu_379_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        bvh_d_index_reg_202 = ap_const_lv6_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_knn_vote_fu_237_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
             esl_seteq<1,1,1>(icmp_ln57_fu_298_p2.read(), ap_const_lv1_1))) {
            grp_knn_vote_fu_237_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_knn_vote_fu_237_ap_ready.read())) {
            grp_knn_vote_fu_237_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln51_fu_242_p2.read(), ap_const_lv1_1))) {
        i4_0_reg_155 = ap_const_lv11_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(icmp_ln59_fu_320_p2.read(), ap_const_lv1_1))) {
        i4_0_reg_155 = i_3_reg_509.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln52_fu_272_p2.read()))) {
        i_0_reg_133 = i_reg_488.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_133 = ap_const_lv4_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        j_0_reg_166 = j_reg_527.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln57_fu_298_p2.read()))) {
        j_0_reg_166 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln51_fu_242_p2.read(), ap_const_lv1_0))) {
        k_0_reg_144 = ap_const_lv2_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln52_fu_272_p2.read()))) {
        k_0_reg_144 = k_fu_278_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(icmp_ln89_fu_373_p2.read(), ap_const_lv1_1))) {
        p_032_0_i_reg_213 = ap_const_lv4_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        p_032_0_i_reg_213 = select_ln96_fu_460_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln89_fu_373_p2.read()))) {
        p_053_0_i_reg_189 = dist_V_fu_396_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        p_053_0_i_reg_189 = ap_const_lv6_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        phi_mul_reg_178 = add_ln59_reg_519.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln57_fu_298_p2.read()))) {
        phi_mul_reg_178 = ap_const_lv15_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(icmp_ln89_fu_373_p2.read(), ap_const_lv1_1))) {
        val_assign_reg_225 = ap_const_lv2_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        val_assign_reg_225 = i_5_fu_468_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        add_ln59_reg_519 = add_ln59_fu_314_p2.read();
        j_reg_527 = j_fu_326_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        i_3_reg_509 = i_3_fu_304_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_488 = i_fu_248_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(icmp_ln95_fu_402_p2.read(), ap_const_lv1_1))) {
        knn_set_V_addr_1_reg_575 =  (sc_lv<5>) (sext_ln895_fu_445_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        ret_V_reg_544 = ret_V_fu_364_p2.read();
        sub_ln895_reg_537 = sub_ln895_fu_354_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln51_fu_242_p2.read(), ap_const_lv1_0))) {
        sub_ln321_reg_493 = sub_ln321_fu_266_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln57_fu_298_p2.read()))) {
        zext_ln59_reg_514 = zext_ln59_fu_310_p1.read();
    }
}

void digitrec::thread_add_ln321_fu_288_p2() {
    add_ln321_fu_288_p2 = (!sub_ln321_reg_493.read().is_01() || !zext_ln321_2_fu_284_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(sub_ln321_reg_493.read()) + sc_biguint<6>(zext_ln321_2_fu_284_p1.read()));
}

void digitrec::thread_add_ln59_fu_314_p2() {
    add_ln59_fu_314_p2 = (!phi_mul_reg_178.read().is_01() || !ap_const_lv15_708.is_01())? sc_lv<15>(): (sc_biguint<15>(phi_mul_reg_178.read()) + sc_biguint<15>(ap_const_lv15_708));
}

void digitrec::thread_add_ln61_fu_332_p2() {
    add_ln61_fu_332_p2 = (!phi_mul_reg_178.read().is_01() || !zext_ln59_reg_514.read().is_01())? sc_lv<15>(): (sc_biguint<15>(phi_mul_reg_178.read()) + sc_biguint<15>(zext_ln59_reg_514.read()));
}

void digitrec::thread_add_ln895_1_fu_412_p2() {
    add_ln895_1_fu_412_p2 = (!sub_ln895_reg_537.read().is_01() || !zext_ln895_1_fu_408_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(sub_ln895_reg_537.read()) + sc_biguint<6>(zext_ln895_1_fu_408_p1.read()));
}

void digitrec::thread_add_ln895_2_fu_426_p2() {
    add_ln895_2_fu_426_p2 = (!sub_ln895_reg_537.read().is_01() || !zext_ln895_2_fu_422_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(sub_ln895_reg_537.read()) + sc_biguint<6>(zext_ln895_2_fu_422_p1.read()));
}

void digitrec::thread_add_ln895_fu_440_p2() {
    add_ln895_fu_440_p2 = (!sub_ln895_reg_537.read().is_01() || !zext_ln895_fu_436_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(sub_ln895_reg_537.read()) + sc_biguint<6>(zext_ln895_fu_436_p1.read()));
}

void digitrec::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void digitrec::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void digitrec::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void digitrec::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void digitrec::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void digitrec::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void digitrec::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void digitrec::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void digitrec::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void digitrec::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void digitrec::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void digitrec::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
          esl_seteq<1,1,1>(grp_knn_vote_fu_237_ap_done.read(), ap_const_logic_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void digitrec::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void digitrec::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(grp_knn_vote_fu_237_ap_done.read(), ap_const_logic_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void digitrec::thread_ap_return() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(grp_knn_vote_fu_237_ap_done.read(), ap_const_logic_1))) {
        ap_return = grp_knn_vote_fu_237_ap_return.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void digitrec::thread_dist_V_fu_396_p2() {
    dist_V_fu_396_p2 = (!zext_ln700_fu_392_p1.read().is_01() || !p_053_0_i_reg_189.read().is_01())? sc_lv<6>(): (sc_biguint<6>(zext_ln700_fu_392_p1.read()) + sc_biguint<6>(p_053_0_i_reg_189.read()));
}

void digitrec::thread_grp_knn_vote_fu_237_ap_start() {
    grp_knn_vote_fu_237_ap_start = grp_knn_vote_fu_237_ap_start_reg.read();
}

void digitrec::thread_i_3_fu_304_p2() {
    i_3_fu_304_p2 = (!i4_0_reg_155.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(i4_0_reg_155.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void digitrec::thread_i_4_fu_379_p2() {
    i_4_fu_379_p2 = (!bvh_d_index_reg_202.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(bvh_d_index_reg_202.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void digitrec::thread_i_5_fu_468_p2() {
    i_5_fu_468_p2 = (!val_assign_reg_225.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(val_assign_reg_225.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void digitrec::thread_i_fu_248_p2() {
    i_fu_248_p2 = (!i_0_reg_133.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_0_reg_133.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void digitrec::thread_icmp_ln51_fu_242_p2() {
    icmp_ln51_fu_242_p2 = (!i_0_reg_133.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_133.read() == ap_const_lv4_A);
}

void digitrec::thread_icmp_ln52_fu_272_p2() {
    icmp_ln52_fu_272_p2 = (!k_0_reg_144.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(k_0_reg_144.read() == ap_const_lv2_3);
}

void digitrec::thread_icmp_ln57_fu_298_p2() {
    icmp_ln57_fu_298_p2 = (!i4_0_reg_155.read().is_01() || !ap_const_lv11_708.is_01())? sc_lv<1>(): sc_lv<1>(i4_0_reg_155.read() == ap_const_lv11_708);
}

void digitrec::thread_icmp_ln59_fu_320_p2() {
    icmp_ln59_fu_320_p2 = (!j_0_reg_166.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(j_0_reg_166.read() == ap_const_lv4_A);
}

void digitrec::thread_icmp_ln895_2_fu_450_p2() {
    icmp_ln895_2_fu_450_p2 = (!knn_set_V_q0.read().is_01() || !knn_set_V_q1.read().is_01())? sc_lv<1>(): (sc_biguint<6>(knn_set_V_q0.read()) > sc_biguint<6>(knn_set_V_q1.read()));
}

void digitrec::thread_icmp_ln895_fu_474_p2() {
    icmp_ln895_fu_474_p2 = (!knn_set_V_q0.read().is_01() || !p_053_0_i_reg_189.read().is_01())? sc_lv<1>(): (sc_biguint<6>(knn_set_V_q0.read()) > sc_biguint<6>(p_053_0_i_reg_189.read()));
}

void digitrec::thread_icmp_ln89_fu_373_p2() {
    icmp_ln89_fu_373_p2 = (!bvh_d_index_reg_202.read().is_01() || !ap_const_lv6_31.is_01())? sc_lv<1>(): sc_lv<1>(bvh_d_index_reg_202.read() == ap_const_lv6_31);
}

void digitrec::thread_icmp_ln95_fu_402_p2() {
    icmp_ln95_fu_402_p2 = (!val_assign_reg_225.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(val_assign_reg_225.read() == ap_const_lv2_3);
}

void digitrec::thread_j_fu_326_p2() {
    j_fu_326_p2 = (!j_0_reg_166.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(j_0_reg_166.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void digitrec::thread_k_fu_278_p2() {
    k_fu_278_p2 = (!k_0_reg_144.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(k_0_reg_144.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void digitrec::thread_knn_set_V_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(icmp_ln95_fu_402_p2.read(), ap_const_lv1_1))) {
        knn_set_V_address0 =  (sc_lv<5>) (sext_ln895_fu_445_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_402_p2.read()))) {
        knn_set_V_address0 =  (sc_lv<5>) (sext_ln895_1_fu_417_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        knn_set_V_address0 =  (sc_lv<5>) (sext_ln321_fu_293_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        knn_set_V_address0 = grp_knn_vote_fu_237_knn_set_V_address0.read();
    } else {
        knn_set_V_address0 = "XXXXX";
    }
}

void digitrec::thread_knn_set_V_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        knn_set_V_address1 = knn_set_V_addr_1_reg_575.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        knn_set_V_address1 =  (sc_lv<5>) (sext_ln895_2_fu_431_p1.read());
    } else {
        knn_set_V_address1 = "XXXXX";
    }
}

void digitrec::thread_knn_set_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_402_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(icmp_ln95_fu_402_p2.read(), ap_const_lv1_1)))) {
        knn_set_V_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        knn_set_V_ce0 = grp_knn_vote_fu_237_knn_set_V_ce0.read();
    } else {
        knn_set_V_ce0 = ap_const_logic_0;
    }
}

void digitrec::thread_knn_set_V_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        knn_set_V_ce1 = ap_const_logic_1;
    } else {
        knn_set_V_ce1 = ap_const_logic_0;
    }
}

void digitrec::thread_knn_set_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln52_fu_272_p2.read()))) {
        knn_set_V_we0 = ap_const_logic_1;
    } else {
        knn_set_V_we0 = ap_const_logic_0;
    }
}

void digitrec::thread_knn_set_V_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln895_fu_474_p2.read()))) {
        knn_set_V_we1 = ap_const_logic_1;
    } else {
        knn_set_V_we1 = ap_const_logic_0;
    }
}

void digitrec::thread_max_idx_V_fu_456_p1() {
    max_idx_V_fu_456_p1 = esl_zext<4,2>(val_assign_reg_225.read());
}

void digitrec::thread_p_Result_s_fu_385_p3() {
    p_Result_s_fu_385_p3 = (!zext_ln89_fu_369_p1.read().is_01() || sc_biguint<32>(zext_ln89_fu_369_p1.read()).to_uint() >= 49)? sc_lv<1>(): ret_V_reg_544.read().range(sc_biguint<32>(zext_ln89_fu_369_p1.read()).to_uint(), sc_biguint<32>(zext_ln89_fu_369_p1.read()).to_uint());
}

void digitrec::thread_ret_V_fu_364_p2() {
    ret_V_fu_364_p2 = (zext_ln61_2_fu_360_p1.read() ^ input_V.read());
}

void digitrec::thread_select_ln96_fu_460_p3() {
    select_ln96_fu_460_p3 = (!icmp_ln895_2_fu_450_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln895_2_fu_450_p2.read()[0].to_bool())? max_idx_V_fu_456_p1.read(): p_032_0_i_reg_213.read());
}

void digitrec::thread_sext_ln321_fu_293_p1() {
    sext_ln321_fu_293_p1 = esl_sext<64,6>(add_ln321_fu_288_p2.read());
}

void digitrec::thread_sext_ln895_1_fu_417_p1() {
    sext_ln895_1_fu_417_p1 = esl_sext<64,6>(add_ln895_1_fu_412_p2.read());
}

void digitrec::thread_sext_ln895_2_fu_431_p1() {
    sext_ln895_2_fu_431_p1 = esl_sext<64,6>(add_ln895_2_fu_426_p2.read());
}

void digitrec::thread_sext_ln895_fu_445_p1() {
    sext_ln895_fu_445_p1 = esl_sext<64,6>(add_ln895_fu_440_p2.read());
}

void digitrec::thread_sub_ln321_fu_266_p2() {
    sub_ln321_fu_266_p2 = (!tmp_3_fu_258_p3.read().is_01() || !zext_ln321_fu_254_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_3_fu_258_p3.read()) - sc_biguint<6>(zext_ln321_fu_254_p1.read()));
}

void digitrec::thread_sub_ln895_fu_354_p2() {
    sub_ln895_fu_354_p2 = (!tmp_4_fu_346_p3.read().is_01() || !zext_ln61_fu_342_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_4_fu_346_p3.read()) - sc_biguint<6>(zext_ln61_fu_342_p1.read()));
}

void digitrec::thread_tmp_3_fu_258_p3() {
    tmp_3_fu_258_p3 = esl_concat<4,2>(i_0_reg_133.read(), ap_const_lv2_0);
}

void digitrec::thread_tmp_4_fu_346_p3() {
    tmp_4_fu_346_p3 = esl_concat<4,2>(j_0_reg_166.read(), ap_const_lv2_0);
}

void digitrec::thread_training_data_V_address0() {
    training_data_V_address0 =  (sc_lv<15>) (zext_ln61_1_fu_337_p1.read());
}

void digitrec::thread_training_data_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        training_data_V_ce0 = ap_const_logic_1;
    } else {
        training_data_V_ce0 = ap_const_logic_0;
    }
}

void digitrec::thread_zext_ln321_2_fu_284_p1() {
    zext_ln321_2_fu_284_p1 = esl_zext<6,2>(k_0_reg_144.read());
}

void digitrec::thread_zext_ln321_fu_254_p1() {
    zext_ln321_fu_254_p1 = esl_zext<6,4>(i_0_reg_133.read());
}

void digitrec::thread_zext_ln59_fu_310_p1() {
    zext_ln59_fu_310_p1 = esl_zext<15,11>(i4_0_reg_155.read());
}

void digitrec::thread_zext_ln61_1_fu_337_p1() {
    zext_ln61_1_fu_337_p1 = esl_zext<64,15>(add_ln61_fu_332_p2.read());
}

void digitrec::thread_zext_ln61_2_fu_360_p1() {
    zext_ln61_2_fu_360_p1 = esl_zext<49,48>(training_data_V_q0.read());
}

void digitrec::thread_zext_ln61_fu_342_p1() {
    zext_ln61_fu_342_p1 = esl_zext<6,4>(j_0_reg_166.read());
}

void digitrec::thread_zext_ln700_fu_392_p1() {
    zext_ln700_fu_392_p1 = esl_zext<6,1>(p_Result_s_fu_385_p3.read());
}

void digitrec::thread_zext_ln895_1_fu_408_p1() {
    zext_ln895_1_fu_408_p1 = esl_zext<6,2>(val_assign_reg_225.read());
}

void digitrec::thread_zext_ln895_2_fu_422_p1() {
    zext_ln895_2_fu_422_p1 = esl_zext<6,4>(p_032_0_i_reg_213.read());
}

void digitrec::thread_zext_ln895_fu_436_p1() {
    zext_ln895_fu_436_p1 = esl_zext<6,4>(p_032_0_i_reg_213.read());
}

void digitrec::thread_zext_ln89_fu_369_p1() {
    zext_ln89_fu_369_p1 = esl_zext<32,6>(bvh_d_index_reg_202.read());
}

void digitrec::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln51_fu_242_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln52_fu_272_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln57_fu_298_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(icmp_ln59_fu_320_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(icmp_ln89_fu_373_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(icmp_ln95_fu_402_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 1024 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(grp_knn_vote_fu_237_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<11>) ("XXXXXXXXXXX");
            break;
    }
}

}

