// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "knn_vote.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic knn_vote::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic knn_vote::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<9> knn_vote::ap_ST_fsm_state1 = "1";
const sc_lv<9> knn_vote::ap_ST_fsm_state2 = "10";
const sc_lv<9> knn_vote::ap_ST_fsm_state3 = "100";
const sc_lv<9> knn_vote::ap_ST_fsm_state4 = "1000";
const sc_lv<9> knn_vote::ap_ST_fsm_state5 = "10000";
const sc_lv<9> knn_vote::ap_ST_fsm_state6 = "100000";
const sc_lv<9> knn_vote::ap_ST_fsm_state7 = "1000000";
const sc_lv<9> knn_vote::ap_ST_fsm_state8 = "10000000";
const sc_lv<9> knn_vote::ap_ST_fsm_state9 = "100000000";
const sc_lv<32> knn_vote::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> knn_vote::ap_const_lv32_2 = "10";
const sc_lv<32> knn_vote::ap_const_lv32_3 = "11";
const sc_lv<1> knn_vote::ap_const_lv1_0 = "0";
const sc_lv<32> knn_vote::ap_const_lv32_4 = "100";
const sc_lv<32> knn_vote::ap_const_lv32_5 = "101";
const sc_lv<1> knn_vote::ap_const_lv1_1 = "1";
const sc_lv<32> knn_vote::ap_const_lv32_6 = "110";
const sc_lv<32> knn_vote::ap_const_lv32_7 = "111";
const sc_lv<2> knn_vote::ap_const_lv2_0 = "00";
const sc_lv<32> knn_vote::ap_const_lv32_1 = "1";
const sc_lv<4> knn_vote::ap_const_lv4_1 = "1";
const sc_lv<4> knn_vote::ap_const_lv4_0 = "0000";
const sc_lv<2> knn_vote::ap_const_lv2_1 = "1";
const sc_lv<4> knn_vote::ap_const_lv4_F = "1111";
const sc_lv<2> knn_vote::ap_const_lv2_3 = "11";
const sc_lv<32> knn_vote::ap_const_lv32_8 = "1000";
const bool knn_vote::ap_const_boolean_1 = true;

knn_vote::knn_vote(sc_module_name name) : sc_module(name), mVcdFile(0) {
    sorted_distances_U = new knn_vote_sorted_dbkb("sorted_distances_U");
    sorted_distances_U->clk(ap_clk);
    sorted_distances_U->reset(ap_rst);
    sorted_distances_U->address0(grp_sort_knn_fu_221_sorted_distances_V_address0);
    sorted_distances_U->ce0(grp_sort_knn_fu_221_sorted_distances_V_ce0);
    sorted_distances_U->we0(grp_sort_knn_fu_221_sorted_distances_V_we0);
    sorted_distances_U->d0(grp_sort_knn_fu_221_sorted_distances_V_d0);
    sorted_distances_U->q0(sorted_distances_q0);
    sorted_distances_U->address1(grp_sort_knn_fu_221_sorted_distances_V_address1);
    sorted_distances_U->ce1(grp_sort_knn_fu_221_sorted_distances_V_ce1);
    sorted_distances_U->we1(grp_sort_knn_fu_221_sorted_distances_V_we1);
    sorted_distances_U->d1(grp_sort_knn_fu_221_sorted_distances_V_d1);
    sorted_distances_U->q1(sorted_distances_q1);
    sorted_labels_U = new knn_vote_sorted_lcud("sorted_labels_U");
    sorted_labels_U->clk(ap_clk);
    sorted_labels_U->reset(ap_rst);
    sorted_labels_U->address0(sorted_labels_address0);
    sorted_labels_U->ce0(sorted_labels_ce0);
    sorted_labels_U->we0(sorted_labels_we0);
    sorted_labels_U->d0(grp_sort_knn_fu_221_sorted_labels_V_d0);
    sorted_labels_U->q0(sorted_labels_q0);
    sorted_labels_U->address1(grp_sort_knn_fu_221_sorted_labels_V_address1);
    sorted_labels_U->ce1(sorted_labels_ce1);
    sorted_labels_U->we1(sorted_labels_we1);
    sorted_labels_U->d1(grp_sort_knn_fu_221_sorted_labels_V_d1);
    sorted_labels_U->q1(sorted_labels_q1);
    grp_sort_knn_fu_221 = new sort_knn("grp_sort_knn_fu_221");
    grp_sort_knn_fu_221->ap_clk(ap_clk);
    grp_sort_knn_fu_221->ap_rst(ap_rst);
    grp_sort_knn_fu_221->ap_start(grp_sort_knn_fu_221_ap_start);
    grp_sort_knn_fu_221->ap_done(grp_sort_knn_fu_221_ap_done);
    grp_sort_knn_fu_221->ap_idle(grp_sort_knn_fu_221_ap_idle);
    grp_sort_knn_fu_221->ap_ready(grp_sort_knn_fu_221_ap_ready);
    grp_sort_knn_fu_221->knn_set_V_address0(grp_sort_knn_fu_221_knn_set_V_address0);
    grp_sort_knn_fu_221->knn_set_V_ce0(grp_sort_knn_fu_221_knn_set_V_ce0);
    grp_sort_knn_fu_221->knn_set_V_q0(knn_set_V_q0);
    grp_sort_knn_fu_221->sorted_distances_V_address0(grp_sort_knn_fu_221_sorted_distances_V_address0);
    grp_sort_knn_fu_221->sorted_distances_V_ce0(grp_sort_knn_fu_221_sorted_distances_V_ce0);
    grp_sort_knn_fu_221->sorted_distances_V_we0(grp_sort_knn_fu_221_sorted_distances_V_we0);
    grp_sort_knn_fu_221->sorted_distances_V_d0(grp_sort_knn_fu_221_sorted_distances_V_d0);
    grp_sort_knn_fu_221->sorted_distances_V_q0(sorted_distances_q0);
    grp_sort_knn_fu_221->sorted_distances_V_address1(grp_sort_knn_fu_221_sorted_distances_V_address1);
    grp_sort_knn_fu_221->sorted_distances_V_ce1(grp_sort_knn_fu_221_sorted_distances_V_ce1);
    grp_sort_knn_fu_221->sorted_distances_V_we1(grp_sort_knn_fu_221_sorted_distances_V_we1);
    grp_sort_knn_fu_221->sorted_distances_V_d1(grp_sort_knn_fu_221_sorted_distances_V_d1);
    grp_sort_knn_fu_221->sorted_distances_V_q1(sorted_distances_q1);
    grp_sort_knn_fu_221->sorted_labels_V_address0(grp_sort_knn_fu_221_sorted_labels_V_address0);
    grp_sort_knn_fu_221->sorted_labels_V_ce0(grp_sort_knn_fu_221_sorted_labels_V_ce0);
    grp_sort_knn_fu_221->sorted_labels_V_we0(grp_sort_knn_fu_221_sorted_labels_V_we0);
    grp_sort_knn_fu_221->sorted_labels_V_d0(grp_sort_knn_fu_221_sorted_labels_V_d0);
    grp_sort_knn_fu_221->sorted_labels_V_q0(sorted_labels_q0);
    grp_sort_knn_fu_221->sorted_labels_V_address1(grp_sort_knn_fu_221_sorted_labels_V_address1);
    grp_sort_knn_fu_221->sorted_labels_V_ce1(grp_sort_knn_fu_221_sorted_labels_V_ce1);
    grp_sort_knn_fu_221->sorted_labels_V_we1(grp_sort_knn_fu_221_sorted_labels_V_we1);
    grp_sort_knn_fu_221->sorted_labels_V_d1(grp_sort_knn_fu_221_sorted_labels_V_d1);
    grp_sort_knn_fu_221->sorted_labels_V_q1(sorted_labels_q1);
    dut_mux_32_4_1_1_U4 = new dut_mux_32_4_1_1<1,1,4,4,4,2,4>("dut_mux_32_4_1_1_U4");
    dut_mux_32_4_1_1_U4->din0(freqs_0_V_reg_167);
    dut_mux_32_4_1_1_U4->din1(freqs_1_V_3_reg_156);
    dut_mux_32_4_1_1_U4->din2(freqs_2_V_3_reg_145);
    dut_mux_32_4_1_1_U4->din3(i3_0_reg_133);
    dut_mux_32_4_1_1_U4->dout(tmp_2_fu_309_p5);
    dut_mux_32_4_1_1_U5 = new dut_mux_32_4_1_1<1,1,4,4,4,2,4>("dut_mux_32_4_1_1_U5");
    dut_mux_32_4_1_1_U5->din0(freqs_0_V_2_reg_123);
    dut_mux_32_4_1_1_U5->din1(freqs_1_V_2_reg_113);
    dut_mux_32_4_1_1_U5->din2(freqs_2_V_2_reg_103);
    dut_mux_32_4_1_1_U5->din3(tmp_1_fu_510_p4);
    dut_mux_32_4_1_1_U5->dout(tmp_1_fu_510_p5);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_phi_mux_i_0_phi_fu_96_p4);
    sensitive << ( i_0_reg_92 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_ap_return);
    sensitive << ( sorted_labels_q0 );
    sensitive << ( ap_return_preg );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_freqs_0_V_0_fu_46);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_phi_mux_i_0_phi_fu_96_p4 );
    sensitive << ( icmp_ln164_fu_240_p2 );

    SC_METHOD(thread_freqs_0_V_3_fu_339_p3);
    sensitive << ( freqs_0_V_reg_167 );
    sensitive << ( t_V_reg_178 );
    sensitive << ( icmp_ln321_1_fu_333_p2 );

    SC_METHOD(thread_freqs_0_V_4_fu_361_p3);
    sensitive << ( freqs_2_V_3_reg_145 );
    sensitive << ( or_ln883_fu_347_p2 );
    sensitive << ( select_ln883_fu_353_p3 );

    SC_METHOD(thread_freqs_0_V_5_fu_377_p3);
    sensitive << ( freqs_1_V_3_reg_156 );
    sensitive << ( or_ln883_fu_347_p2 );
    sensitive << ( select_ln883_2_fu_369_p3 );

    SC_METHOD(thread_freqs_0_V_6_fu_385_p3);
    sensitive << ( freqs_0_V_reg_167 );
    sensitive << ( icmp_ln883_fu_321_p2 );
    sensitive << ( freqs_0_V_3_fu_339_p3 );

    SC_METHOD(thread_freqs_1_V_0_fu_50);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_phi_mux_i_0_phi_fu_96_p4 );
    sensitive << ( icmp_ln164_fu_240_p2 );

    SC_METHOD(thread_freqs_2_V_0_fu_54);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_phi_mux_i_0_phi_fu_96_p4 );
    sensitive << ( icmp_ln164_fu_240_p2 );

    SC_METHOD(thread_grp_sort_knn_fu_221_ap_start);
    sensitive << ( grp_sort_knn_fu_221_ap_start_reg );

    SC_METHOD(thread_i_1_fu_540_p2);
    sensitive << ( val_assign_reg_210 );

    SC_METHOD(thread_i_2_fu_277_p2);
    sensitive << ( i3_0_reg_133 );

    SC_METHOD(thread_i_fu_246_p2);
    sensitive << ( i_0_reg_92 );

    SC_METHOD(thread_icmp_ln164_fu_240_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( i_0_reg_92 );

    SC_METHOD(thread_icmp_ln169_fu_271_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( i3_0_reg_133 );

    SC_METHOD(thread_icmp_ln171_fu_298_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( j_0_in_reg_190 );

    SC_METHOD(thread_icmp_ln182_fu_486_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( val_assign_reg_210 );

    SC_METHOD(thread_icmp_ln321_1_fu_333_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln171_fu_298_p2 );
    sensitive << ( i3_0_reg_133 );

    SC_METHOD(thread_icmp_ln321_2_fu_404_p2);
    sensitive << ( trunc_ln171_reg_615 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_icmp_ln321_3_fu_417_p2);
    sensitive << ( trunc_ln171_reg_615 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_icmp_ln321_fu_327_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln171_fu_298_p2 );
    sensitive << ( i3_0_reg_133 );

    SC_METHOD(thread_icmp_ln879_fu_393_p2);
    sensitive << ( sorted_labels_q0 );
    sensitive << ( sorted_labels_load_1_reg_610 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_icmp_ln883_fu_321_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln171_fu_298_p2 );
    sensitive << ( tmp_2_fu_309_p5 );

    SC_METHOD(thread_icmp_ln895_1_fu_492_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln182_fu_486_p2 );
    sensitive << ( val_assign_reg_210 );

    SC_METHOD(thread_icmp_ln895_fu_522_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln182_fu_486_p2 );
    sensitive << ( select_ln895_fu_498_p3 );
    sensitive << ( tmp_1_fu_510_p5 );

    SC_METHOD(thread_j_fu_292_p2);
    sensitive << ( j_0_in_reg_190 );

    SC_METHOD(thread_knn_set_V_address0);
    sensitive << ( grp_sort_knn_fu_221_knn_set_V_address0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_knn_set_V_ce0);
    sensitive << ( grp_sort_knn_fu_221_knn_set_V_ce0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_local_cnt_V_1_fu_478_p3);
    sensitive << ( t_V_reg_178 );
    sensitive << ( icmp_ln879_fu_393_p2 );
    sensitive << ( local_cnt_V_fu_398_p2 );

    SC_METHOD(thread_local_cnt_V_fu_398_p2);
    sensitive << ( t_V_reg_178 );

    SC_METHOD(thread_max_idx_V_fu_528_p1);
    sensitive << ( val_assign_reg_210 );

    SC_METHOD(thread_or_ln883_fu_347_p2);
    sensitive << ( icmp_ln321_1_fu_333_p2 );
    sensitive << ( icmp_ln883_fu_321_p2 );

    SC_METHOD(thread_select_ln183_fu_532_p3);
    sensitive << ( p_022_0_reg_199 );
    sensitive << ( icmp_ln895_fu_522_p2 );
    sensitive << ( max_idx_V_fu_528_p1 );

    SC_METHOD(thread_select_ln321_1_fu_422_p3);
    sensitive << ( freqs_2_V_3_reg_145 );
    sensitive << ( icmp_ln321_3_fu_417_p2 );
    sensitive << ( select_ln321_fu_409_p3 );

    SC_METHOD(thread_select_ln321_2_fu_430_p3);
    sensitive << ( freqs_1_V_3_reg_156 );
    sensitive << ( icmp_ln321_2_fu_404_p2 );

    SC_METHOD(thread_select_ln321_3_fu_438_p3);
    sensitive << ( freqs_1_V_3_reg_156 );
    sensitive << ( icmp_ln321_3_fu_417_p2 );
    sensitive << ( select_ln321_2_fu_430_p3 );

    SC_METHOD(thread_select_ln321_4_fu_446_p3);
    sensitive << ( freqs_0_V_reg_167 );
    sensitive << ( icmp_ln321_3_fu_417_p2 );

    SC_METHOD(thread_select_ln321_fu_409_p3);
    sensitive << ( freqs_2_V_3_reg_145 );
    sensitive << ( icmp_ln321_2_fu_404_p2 );

    SC_METHOD(thread_select_ln879_1_fu_462_p3);
    sensitive << ( freqs_1_V_3_reg_156 );
    sensitive << ( icmp_ln879_fu_393_p2 );
    sensitive << ( select_ln321_3_fu_438_p3 );

    SC_METHOD(thread_select_ln879_2_fu_470_p3);
    sensitive << ( freqs_0_V_reg_167 );
    sensitive << ( icmp_ln879_fu_393_p2 );
    sensitive << ( select_ln321_4_fu_446_p3 );

    SC_METHOD(thread_select_ln879_fu_454_p3);
    sensitive << ( freqs_2_V_3_reg_145 );
    sensitive << ( icmp_ln879_fu_393_p2 );
    sensitive << ( select_ln321_1_fu_422_p3 );

    SC_METHOD(thread_select_ln883_2_fu_369_p3);
    sensitive << ( freqs_1_V_3_reg_156 );
    sensitive << ( t_V_reg_178 );
    sensitive << ( icmp_ln321_fu_327_p2 );

    SC_METHOD(thread_select_ln883_fu_353_p3);
    sensitive << ( freqs_2_V_3_reg_145 );
    sensitive << ( t_V_reg_178 );
    sensitive << ( icmp_ln321_fu_327_p2 );

    SC_METHOD(thread_select_ln895_fu_498_p3);
    sensitive << ( freqs_2_V_2_reg_103 );
    sensitive << ( freqs_1_V_2_reg_113 );
    sensitive << ( icmp_ln895_1_fu_492_p2 );

    SC_METHOD(thread_sext_ln172_fu_304_p1);
    sensitive << ( j_fu_292_p2 );

    SC_METHOD(thread_sorted_labels_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( grp_sort_knn_fu_221_sorted_labels_V_address0 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln172_fu_283_p1 );
    sensitive << ( sext_ln172_fu_304_p1 );
    sensitive << ( zext_ln544_fu_546_p1 );

    SC_METHOD(thread_sorted_labels_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( grp_sort_knn_fu_221_sorted_labels_V_ce0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_sorted_labels_ce1);
    sensitive << ( grp_sort_knn_fu_221_sorted_labels_V_ce1 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_sorted_labels_we0);
    sensitive << ( grp_sort_knn_fu_221_sorted_labels_V_we0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_sorted_labels_we1);
    sensitive << ( grp_sort_knn_fu_221_sorted_labels_V_we1 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_tmp_1_fu_510_p4);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( p_022_0_reg_199 );

    SC_METHOD(thread_trunc_ln171_fu_288_p1);
    sensitive << ( j_0_in_reg_190 );

    SC_METHOD(thread_zext_ln169_fu_267_p1);
    sensitive << ( i3_0_reg_133 );

    SC_METHOD(thread_zext_ln172_fu_283_p1);
    sensitive << ( i3_0_reg_133 );

    SC_METHOD(thread_zext_ln544_fu_546_p1);
    sensitive << ( p_022_0_reg_199 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln169_fu_271_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln171_fu_298_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln182_fu_486_p2 );
    sensitive << ( grp_sort_knn_fu_221_ap_done );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln164_fu_240_p2 );

    ap_CS_fsm = "000000001";
    grp_sort_knn_fu_221_ap_start_reg = SC_LOGIC_0;
    ap_return_preg = "0000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "knn_vote_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, knn_set_V_address0, "(port)knn_set_V_address0");
    sc_trace(mVcdFile, knn_set_V_ce0, "(port)knn_set_V_ce0");
    sc_trace(mVcdFile, knn_set_V_q0, "(port)knn_set_V_q0");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, i_fu_246_p2, "i_fu_246_p2");
    sc_trace(mVcdFile, zext_ln169_fu_267_p1, "zext_ln169_fu_267_p1");
    sc_trace(mVcdFile, zext_ln169_reg_592, "zext_ln169_reg_592");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, i_2_fu_277_p2, "i_2_fu_277_p2");
    sc_trace(mVcdFile, i_2_reg_600, "i_2_reg_600");
    sc_trace(mVcdFile, icmp_ln169_fu_271_p2, "icmp_ln169_fu_271_p2");
    sc_trace(mVcdFile, sorted_labels_q0, "sorted_labels_q0");
    sc_trace(mVcdFile, sorted_labels_load_1_reg_610, "sorted_labels_load_1_reg_610");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, trunc_ln171_fu_288_p1, "trunc_ln171_fu_288_p1");
    sc_trace(mVcdFile, trunc_ln171_reg_615, "trunc_ln171_reg_615");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, j_fu_292_p2, "j_fu_292_p2");
    sc_trace(mVcdFile, j_reg_621, "j_reg_621");
    sc_trace(mVcdFile, icmp_ln171_fu_298_p2, "icmp_ln171_fu_298_p2");
    sc_trace(mVcdFile, freqs_0_V_4_fu_361_p3, "freqs_0_V_4_fu_361_p3");
    sc_trace(mVcdFile, freqs_0_V_5_fu_377_p3, "freqs_0_V_5_fu_377_p3");
    sc_trace(mVcdFile, freqs_0_V_6_fu_385_p3, "freqs_0_V_6_fu_385_p3");
    sc_trace(mVcdFile, select_ln879_fu_454_p3, "select_ln879_fu_454_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, select_ln879_1_fu_462_p3, "select_ln879_1_fu_462_p3");
    sc_trace(mVcdFile, select_ln879_2_fu_470_p3, "select_ln879_2_fu_470_p3");
    sc_trace(mVcdFile, local_cnt_V_1_fu_478_p3, "local_cnt_V_1_fu_478_p3");
    sc_trace(mVcdFile, select_ln183_fu_532_p3, "select_ln183_fu_532_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, icmp_ln182_fu_486_p2, "icmp_ln182_fu_486_p2");
    sc_trace(mVcdFile, i_1_fu_540_p2, "i_1_fu_540_p2");
    sc_trace(mVcdFile, sorted_distances_q0, "sorted_distances_q0");
    sc_trace(mVcdFile, sorted_distances_q1, "sorted_distances_q1");
    sc_trace(mVcdFile, sorted_labels_address0, "sorted_labels_address0");
    sc_trace(mVcdFile, sorted_labels_ce0, "sorted_labels_ce0");
    sc_trace(mVcdFile, sorted_labels_we0, "sorted_labels_we0");
    sc_trace(mVcdFile, sorted_labels_ce1, "sorted_labels_ce1");
    sc_trace(mVcdFile, sorted_labels_we1, "sorted_labels_we1");
    sc_trace(mVcdFile, sorted_labels_q1, "sorted_labels_q1");
    sc_trace(mVcdFile, grp_sort_knn_fu_221_ap_start, "grp_sort_knn_fu_221_ap_start");
    sc_trace(mVcdFile, grp_sort_knn_fu_221_ap_done, "grp_sort_knn_fu_221_ap_done");
    sc_trace(mVcdFile, grp_sort_knn_fu_221_ap_idle, "grp_sort_knn_fu_221_ap_idle");
    sc_trace(mVcdFile, grp_sort_knn_fu_221_ap_ready, "grp_sort_knn_fu_221_ap_ready");
    sc_trace(mVcdFile, grp_sort_knn_fu_221_knn_set_V_address0, "grp_sort_knn_fu_221_knn_set_V_address0");
    sc_trace(mVcdFile, grp_sort_knn_fu_221_knn_set_V_ce0, "grp_sort_knn_fu_221_knn_set_V_ce0");
    sc_trace(mVcdFile, grp_sort_knn_fu_221_sorted_distances_V_address0, "grp_sort_knn_fu_221_sorted_distances_V_address0");
    sc_trace(mVcdFile, grp_sort_knn_fu_221_sorted_distances_V_ce0, "grp_sort_knn_fu_221_sorted_distances_V_ce0");
    sc_trace(mVcdFile, grp_sort_knn_fu_221_sorted_distances_V_we0, "grp_sort_knn_fu_221_sorted_distances_V_we0");
    sc_trace(mVcdFile, grp_sort_knn_fu_221_sorted_distances_V_d0, "grp_sort_knn_fu_221_sorted_distances_V_d0");
    sc_trace(mVcdFile, grp_sort_knn_fu_221_sorted_distances_V_address1, "grp_sort_knn_fu_221_sorted_distances_V_address1");
    sc_trace(mVcdFile, grp_sort_knn_fu_221_sorted_distances_V_ce1, "grp_sort_knn_fu_221_sorted_distances_V_ce1");
    sc_trace(mVcdFile, grp_sort_knn_fu_221_sorted_distances_V_we1, "grp_sort_knn_fu_221_sorted_distances_V_we1");
    sc_trace(mVcdFile, grp_sort_knn_fu_221_sorted_distances_V_d1, "grp_sort_knn_fu_221_sorted_distances_V_d1");
    sc_trace(mVcdFile, grp_sort_knn_fu_221_sorted_labels_V_address0, "grp_sort_knn_fu_221_sorted_labels_V_address0");
    sc_trace(mVcdFile, grp_sort_knn_fu_221_sorted_labels_V_ce0, "grp_sort_knn_fu_221_sorted_labels_V_ce0");
    sc_trace(mVcdFile, grp_sort_knn_fu_221_sorted_labels_V_we0, "grp_sort_knn_fu_221_sorted_labels_V_we0");
    sc_trace(mVcdFile, grp_sort_knn_fu_221_sorted_labels_V_d0, "grp_sort_knn_fu_221_sorted_labels_V_d0");
    sc_trace(mVcdFile, grp_sort_knn_fu_221_sorted_labels_V_address1, "grp_sort_knn_fu_221_sorted_labels_V_address1");
    sc_trace(mVcdFile, grp_sort_knn_fu_221_sorted_labels_V_ce1, "grp_sort_knn_fu_221_sorted_labels_V_ce1");
    sc_trace(mVcdFile, grp_sort_knn_fu_221_sorted_labels_V_we1, "grp_sort_knn_fu_221_sorted_labels_V_we1");
    sc_trace(mVcdFile, grp_sort_knn_fu_221_sorted_labels_V_d1, "grp_sort_knn_fu_221_sorted_labels_V_d1");
    sc_trace(mVcdFile, ap_phi_mux_i_0_phi_fu_96_p4, "ap_phi_mux_i_0_phi_fu_96_p4");
    sc_trace(mVcdFile, i_0_reg_92, "i_0_reg_92");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, icmp_ln164_fu_240_p2, "icmp_ln164_fu_240_p2");
    sc_trace(mVcdFile, freqs_2_V_2_reg_103, "freqs_2_V_2_reg_103");
    sc_trace(mVcdFile, freqs_1_V_2_reg_113, "freqs_1_V_2_reg_113");
    sc_trace(mVcdFile, freqs_0_V_2_reg_123, "freqs_0_V_2_reg_123");
    sc_trace(mVcdFile, i3_0_reg_133, "i3_0_reg_133");
    sc_trace(mVcdFile, freqs_2_V_3_reg_145, "freqs_2_V_3_reg_145");
    sc_trace(mVcdFile, freqs_1_V_3_reg_156, "freqs_1_V_3_reg_156");
    sc_trace(mVcdFile, freqs_0_V_reg_167, "freqs_0_V_reg_167");
    sc_trace(mVcdFile, t_V_reg_178, "t_V_reg_178");
    sc_trace(mVcdFile, j_0_in_reg_190, "j_0_in_reg_190");
    sc_trace(mVcdFile, p_022_0_reg_199, "p_022_0_reg_199");
    sc_trace(mVcdFile, val_assign_reg_210, "val_assign_reg_210");
    sc_trace(mVcdFile, grp_sort_knn_fu_221_ap_start_reg, "grp_sort_knn_fu_221_ap_start_reg");
    sc_trace(mVcdFile, zext_ln172_fu_283_p1, "zext_ln172_fu_283_p1");
    sc_trace(mVcdFile, sext_ln172_fu_304_p1, "sext_ln172_fu_304_p1");
    sc_trace(mVcdFile, zext_ln544_fu_546_p1, "zext_ln544_fu_546_p1");
    sc_trace(mVcdFile, freqs_0_V_0_fu_46, "freqs_0_V_0_fu_46");
    sc_trace(mVcdFile, freqs_1_V_0_fu_50, "freqs_1_V_0_fu_50");
    sc_trace(mVcdFile, freqs_2_V_0_fu_54, "freqs_2_V_0_fu_54");
    sc_trace(mVcdFile, tmp_2_fu_309_p5, "tmp_2_fu_309_p5");
    sc_trace(mVcdFile, icmp_ln321_1_fu_333_p2, "icmp_ln321_1_fu_333_p2");
    sc_trace(mVcdFile, icmp_ln883_fu_321_p2, "icmp_ln883_fu_321_p2");
    sc_trace(mVcdFile, icmp_ln321_fu_327_p2, "icmp_ln321_fu_327_p2");
    sc_trace(mVcdFile, or_ln883_fu_347_p2, "or_ln883_fu_347_p2");
    sc_trace(mVcdFile, select_ln883_fu_353_p3, "select_ln883_fu_353_p3");
    sc_trace(mVcdFile, select_ln883_2_fu_369_p3, "select_ln883_2_fu_369_p3");
    sc_trace(mVcdFile, freqs_0_V_3_fu_339_p3, "freqs_0_V_3_fu_339_p3");
    sc_trace(mVcdFile, icmp_ln321_2_fu_404_p2, "icmp_ln321_2_fu_404_p2");
    sc_trace(mVcdFile, icmp_ln321_3_fu_417_p2, "icmp_ln321_3_fu_417_p2");
    sc_trace(mVcdFile, select_ln321_fu_409_p3, "select_ln321_fu_409_p3");
    sc_trace(mVcdFile, select_ln321_2_fu_430_p3, "select_ln321_2_fu_430_p3");
    sc_trace(mVcdFile, icmp_ln879_fu_393_p2, "icmp_ln879_fu_393_p2");
    sc_trace(mVcdFile, select_ln321_1_fu_422_p3, "select_ln321_1_fu_422_p3");
    sc_trace(mVcdFile, select_ln321_3_fu_438_p3, "select_ln321_3_fu_438_p3");
    sc_trace(mVcdFile, select_ln321_4_fu_446_p3, "select_ln321_4_fu_446_p3");
    sc_trace(mVcdFile, local_cnt_V_fu_398_p2, "local_cnt_V_fu_398_p2");
    sc_trace(mVcdFile, icmp_ln895_1_fu_492_p2, "icmp_ln895_1_fu_492_p2");
    sc_trace(mVcdFile, tmp_1_fu_510_p4, "tmp_1_fu_510_p4");
    sc_trace(mVcdFile, select_ln895_fu_498_p3, "select_ln895_fu_498_p3");
    sc_trace(mVcdFile, tmp_1_fu_510_p5, "tmp_1_fu_510_p5");
    sc_trace(mVcdFile, icmp_ln895_fu_522_p2, "icmp_ln895_fu_522_p2");
    sc_trace(mVcdFile, max_idx_V_fu_528_p1, "max_idx_V_fu_528_p1");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

knn_vote::~knn_vote() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete sorted_distances_U;
    delete sorted_labels_U;
    delete grp_sort_knn_fu_221;
    delete dut_mux_32_4_1_1_U4;
    delete dut_mux_32_4_1_1_U5;
}

void knn_vote::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv4_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
            ap_return_preg = sorted_labels_q0.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln164_fu_240_p2.read()))) {
        freqs_0_V_2_reg_123 = freqs_0_V_0_fu_46.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(icmp_ln171_fu_298_p2.read(), ap_const_lv1_1))) {
        freqs_0_V_2_reg_123 = freqs_0_V_6_fu_385_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        freqs_0_V_reg_167 = select_ln879_2_fu_470_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        freqs_0_V_reg_167 = freqs_0_V_2_reg_123.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln164_fu_240_p2.read()))) {
        freqs_1_V_2_reg_113 = freqs_1_V_0_fu_50.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(icmp_ln171_fu_298_p2.read(), ap_const_lv1_1))) {
        freqs_1_V_2_reg_113 = freqs_0_V_5_fu_377_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        freqs_1_V_3_reg_156 = select_ln879_1_fu_462_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        freqs_1_V_3_reg_156 = freqs_1_V_2_reg_113.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln164_fu_240_p2.read()))) {
        freqs_2_V_2_reg_103 = freqs_2_V_0_fu_54.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(icmp_ln171_fu_298_p2.read(), ap_const_lv1_1))) {
        freqs_2_V_2_reg_103 = freqs_0_V_4_fu_361_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        freqs_2_V_3_reg_145 = select_ln879_fu_454_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        freqs_2_V_3_reg_145 = freqs_2_V_2_reg_103.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_sort_knn_fu_221_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            grp_sort_knn_fu_221_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_sort_knn_fu_221_ap_ready.read())) {
            grp_sort_knn_fu_221_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln164_fu_240_p2.read()))) {
        i3_0_reg_133 = ap_const_lv2_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(icmp_ln171_fu_298_p2.read(), ap_const_lv1_1))) {
        i3_0_reg_133 = i_2_reg_600.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln164_fu_240_p2.read()))) {
        i_0_reg_92 = i_fu_246_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(grp_sort_knn_fu_221_ap_done.read(), ap_const_logic_1))) {
        i_0_reg_92 = ap_const_lv2_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        j_0_in_reg_190 = j_reg_621.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        j_0_in_reg_190 = zext_ln169_reg_592.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln169_fu_271_p2.read(), ap_const_lv1_1))) {
        p_022_0_reg_199 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln182_fu_486_p2.read()))) {
        p_022_0_reg_199 = select_ln183_fu_532_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        t_V_reg_178 = local_cnt_V_1_fu_478_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        t_V_reg_178 = ap_const_lv4_1;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln169_fu_271_p2.read(), ap_const_lv1_1))) {
        val_assign_reg_210 = ap_const_lv2_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln182_fu_486_p2.read()))) {
        val_assign_reg_210 = i_1_fu_540_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        i_2_reg_600 = i_2_fu_277_p2.read();
        zext_ln169_reg_592 = zext_ln169_fu_267_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        j_reg_621 = j_fu_292_p2.read();
        trunc_ln171_reg_615 = trunc_ln171_fu_288_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        sorted_labels_load_1_reg_610 = sorted_labels_q0.read();
    }
}

void knn_vote::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void knn_vote::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void knn_vote::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void knn_vote::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void knn_vote::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void knn_vote::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void knn_vote::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void knn_vote::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void knn_vote::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void knn_vote::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void knn_vote::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void knn_vote::thread_ap_phi_mux_i_0_phi_fu_96_p4() {
    ap_phi_mux_i_0_phi_fu_96_p4 = i_0_reg_92.read();
}

void knn_vote::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void knn_vote::thread_ap_return() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        ap_return = sorted_labels_q0.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void knn_vote::thread_freqs_0_V_0_fu_46() {
    freqs_0_V_0_fu_46 = ap_const_lv4_F;
}

void knn_vote::thread_freqs_0_V_3_fu_339_p3() {
    freqs_0_V_3_fu_339_p3 = (!icmp_ln321_1_fu_333_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln321_1_fu_333_p2.read()[0].to_bool())? t_V_reg_178.read(): freqs_0_V_reg_167.read());
}

void knn_vote::thread_freqs_0_V_4_fu_361_p3() {
    freqs_0_V_4_fu_361_p3 = (!or_ln883_fu_347_p2.read()[0].is_01())? sc_lv<4>(): ((or_ln883_fu_347_p2.read()[0].to_bool())? freqs_2_V_3_reg_145.read(): select_ln883_fu_353_p3.read());
}

void knn_vote::thread_freqs_0_V_5_fu_377_p3() {
    freqs_0_V_5_fu_377_p3 = (!or_ln883_fu_347_p2.read()[0].is_01())? sc_lv<4>(): ((or_ln883_fu_347_p2.read()[0].to_bool())? freqs_1_V_3_reg_156.read(): select_ln883_2_fu_369_p3.read());
}

void knn_vote::thread_freqs_0_V_6_fu_385_p3() {
    freqs_0_V_6_fu_385_p3 = (!icmp_ln883_fu_321_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln883_fu_321_p2.read()[0].to_bool())? freqs_0_V_reg_167.read(): freqs_0_V_3_fu_339_p3.read());
}

void knn_vote::thread_freqs_1_V_0_fu_50() {
    freqs_1_V_0_fu_50 = ap_const_lv4_F;
}

void knn_vote::thread_freqs_2_V_0_fu_54() {
    freqs_2_V_0_fu_54 = ap_const_lv4_F;
}

void knn_vote::thread_grp_sort_knn_fu_221_ap_start() {
    grp_sort_knn_fu_221_ap_start = grp_sort_knn_fu_221_ap_start_reg.read();
}

void knn_vote::thread_i_1_fu_540_p2() {
    i_1_fu_540_p2 = (!ap_const_lv2_1.is_01() || !val_assign_reg_210.read().is_01())? sc_lv<2>(): (sc_biguint<2>(ap_const_lv2_1) + sc_biguint<2>(val_assign_reg_210.read()));
}

void knn_vote::thread_i_2_fu_277_p2() {
    i_2_fu_277_p2 = (!i3_0_reg_133.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i3_0_reg_133.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void knn_vote::thread_i_fu_246_p2() {
    i_fu_246_p2 = (!i_0_reg_92.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i_0_reg_92.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void knn_vote::thread_icmp_ln164_fu_240_p2() {
    icmp_ln164_fu_240_p2 = (!i_0_reg_92.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_92.read() == ap_const_lv2_3);
}

void knn_vote::thread_icmp_ln169_fu_271_p2() {
    icmp_ln169_fu_271_p2 = (!i3_0_reg_133.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(i3_0_reg_133.read() == ap_const_lv2_3);
}

void knn_vote::thread_icmp_ln171_fu_298_p2() {
    icmp_ln171_fu_298_p2 = (!j_0_in_reg_190.read().is_01() || !ap_const_lv32_2.is_01())? sc_lv<1>(): sc_lv<1>(j_0_in_reg_190.read() == ap_const_lv32_2);
}

void knn_vote::thread_icmp_ln182_fu_486_p2() {
    icmp_ln182_fu_486_p2 = (!val_assign_reg_210.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(val_assign_reg_210.read() == ap_const_lv2_3);
}

void knn_vote::thread_icmp_ln321_1_fu_333_p2() {
    icmp_ln321_1_fu_333_p2 = (!i3_0_reg_133.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(i3_0_reg_133.read() == ap_const_lv2_0);
}

void knn_vote::thread_icmp_ln321_2_fu_404_p2() {
    icmp_ln321_2_fu_404_p2 = (!trunc_ln171_reg_615.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln171_reg_615.read() == ap_const_lv2_0);
}

void knn_vote::thread_icmp_ln321_3_fu_417_p2() {
    icmp_ln321_3_fu_417_p2 = (!trunc_ln171_reg_615.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln171_reg_615.read() == ap_const_lv2_3);
}

void knn_vote::thread_icmp_ln321_fu_327_p2() {
    icmp_ln321_fu_327_p2 = (!i3_0_reg_133.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(i3_0_reg_133.read() == ap_const_lv2_1);
}

void knn_vote::thread_icmp_ln879_fu_393_p2() {
    icmp_ln879_fu_393_p2 = (!sorted_labels_load_1_reg_610.read().is_01() || !sorted_labels_q0.read().is_01())? sc_lv<1>(): sc_lv<1>(sorted_labels_load_1_reg_610.read() == sorted_labels_q0.read());
}

void knn_vote::thread_icmp_ln883_fu_321_p2() {
    icmp_ln883_fu_321_p2 = (!tmp_2_fu_309_p5.read().is_01() || !ap_const_lv4_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_2_fu_309_p5.read() == ap_const_lv4_0);
}

void knn_vote::thread_icmp_ln895_1_fu_492_p2() {
    icmp_ln895_1_fu_492_p2 = (!val_assign_reg_210.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(val_assign_reg_210.read() == ap_const_lv2_1);
}

void knn_vote::thread_icmp_ln895_fu_522_p2() {
    icmp_ln895_fu_522_p2 = (!select_ln895_fu_498_p3.read().is_01() || !tmp_1_fu_510_p5.read().is_01())? sc_lv<1>(): (sc_biguint<4>(select_ln895_fu_498_p3.read()) > sc_biguint<4>(tmp_1_fu_510_p5.read()));
}

void knn_vote::thread_j_fu_292_p2() {
    j_fu_292_p2 = (!ap_const_lv32_1.is_01() || !j_0_in_reg_190.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1) + sc_biguint<32>(j_0_in_reg_190.read()));
}

void knn_vote::thread_knn_set_V_address0() {
    knn_set_V_address0 = grp_sort_knn_fu_221_knn_set_V_address0.read();
}

void knn_vote::thread_knn_set_V_ce0() {
    knn_set_V_ce0 = grp_sort_knn_fu_221_knn_set_V_ce0.read();
}

void knn_vote::thread_local_cnt_V_1_fu_478_p3() {
    local_cnt_V_1_fu_478_p3 = (!icmp_ln879_fu_393_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln879_fu_393_p2.read()[0].to_bool())? local_cnt_V_fu_398_p2.read(): t_V_reg_178.read());
}

void knn_vote::thread_local_cnt_V_fu_398_p2() {
    local_cnt_V_fu_398_p2 = (!t_V_reg_178.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(t_V_reg_178.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void knn_vote::thread_max_idx_V_fu_528_p1() {
    max_idx_V_fu_528_p1 = esl_zext<4,2>(val_assign_reg_210.read());
}

void knn_vote::thread_or_ln883_fu_347_p2() {
    or_ln883_fu_347_p2 = (icmp_ln883_fu_321_p2.read() | icmp_ln321_1_fu_333_p2.read());
}

void knn_vote::thread_select_ln183_fu_532_p3() {
    select_ln183_fu_532_p3 = (!icmp_ln895_fu_522_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln895_fu_522_p2.read()[0].to_bool())? max_idx_V_fu_528_p1.read(): p_022_0_reg_199.read());
}

void knn_vote::thread_select_ln321_1_fu_422_p3() {
    select_ln321_1_fu_422_p3 = (!icmp_ln321_3_fu_417_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln321_3_fu_417_p2.read()[0].to_bool())? freqs_2_V_3_reg_145.read(): select_ln321_fu_409_p3.read());
}

void knn_vote::thread_select_ln321_2_fu_430_p3() {
    select_ln321_2_fu_430_p3 = (!icmp_ln321_2_fu_404_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln321_2_fu_404_p2.read()[0].to_bool())? ap_const_lv4_0: freqs_1_V_3_reg_156.read());
}

void knn_vote::thread_select_ln321_3_fu_438_p3() {
    select_ln321_3_fu_438_p3 = (!icmp_ln321_3_fu_417_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln321_3_fu_417_p2.read()[0].to_bool())? freqs_1_V_3_reg_156.read(): select_ln321_2_fu_430_p3.read());
}

void knn_vote::thread_select_ln321_4_fu_446_p3() {
    select_ln321_4_fu_446_p3 = (!icmp_ln321_3_fu_417_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln321_3_fu_417_p2.read()[0].to_bool())? ap_const_lv4_0: freqs_0_V_reg_167.read());
}

void knn_vote::thread_select_ln321_fu_409_p3() {
    select_ln321_fu_409_p3 = (!icmp_ln321_2_fu_404_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln321_2_fu_404_p2.read()[0].to_bool())? freqs_2_V_3_reg_145.read(): ap_const_lv4_0);
}

void knn_vote::thread_select_ln879_1_fu_462_p3() {
    select_ln879_1_fu_462_p3 = (!icmp_ln879_fu_393_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln879_fu_393_p2.read()[0].to_bool())? select_ln321_3_fu_438_p3.read(): freqs_1_V_3_reg_156.read());
}

void knn_vote::thread_select_ln879_2_fu_470_p3() {
    select_ln879_2_fu_470_p3 = (!icmp_ln879_fu_393_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln879_fu_393_p2.read()[0].to_bool())? select_ln321_4_fu_446_p3.read(): freqs_0_V_reg_167.read());
}

void knn_vote::thread_select_ln879_fu_454_p3() {
    select_ln879_fu_454_p3 = (!icmp_ln879_fu_393_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln879_fu_393_p2.read()[0].to_bool())? select_ln321_1_fu_422_p3.read(): freqs_2_V_3_reg_145.read());
}

void knn_vote::thread_select_ln883_2_fu_369_p3() {
    select_ln883_2_fu_369_p3 = (!icmp_ln321_fu_327_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln321_fu_327_p2.read()[0].to_bool())? t_V_reg_178.read(): freqs_1_V_3_reg_156.read());
}

void knn_vote::thread_select_ln883_fu_353_p3() {
    select_ln883_fu_353_p3 = (!icmp_ln321_fu_327_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln321_fu_327_p2.read()[0].to_bool())? freqs_2_V_3_reg_145.read(): t_V_reg_178.read());
}

void knn_vote::thread_select_ln895_fu_498_p3() {
    select_ln895_fu_498_p3 = (!icmp_ln895_1_fu_492_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln895_1_fu_492_p2.read()[0].to_bool())? freqs_1_V_2_reg_113.read(): freqs_2_V_2_reg_103.read());
}

void knn_vote::thread_sext_ln172_fu_304_p1() {
    sext_ln172_fu_304_p1 = esl_sext<64,32>(j_fu_292_p2.read());
}

void knn_vote::thread_sorted_labels_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        sorted_labels_address0 =  (sc_lv<5>) (zext_ln544_fu_546_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        sorted_labels_address0 =  (sc_lv<5>) (sext_ln172_fu_304_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        sorted_labels_address0 =  (sc_lv<5>) (zext_ln172_fu_283_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        sorted_labels_address0 = grp_sort_knn_fu_221_sorted_labels_V_address0.read();
    } else {
        sorted_labels_address0 = "XXXXX";
    }
}

void knn_vote::thread_sorted_labels_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        sorted_labels_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        sorted_labels_ce0 = grp_sort_knn_fu_221_sorted_labels_V_ce0.read();
    } else {
        sorted_labels_ce0 = ap_const_logic_0;
    }
}

void knn_vote::thread_sorted_labels_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        sorted_labels_ce1 = grp_sort_knn_fu_221_sorted_labels_V_ce1.read();
    } else {
        sorted_labels_ce1 = ap_const_logic_0;
    }
}

void knn_vote::thread_sorted_labels_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        sorted_labels_we0 = grp_sort_knn_fu_221_sorted_labels_V_we0.read();
    } else {
        sorted_labels_we0 = ap_const_logic_0;
    }
}

void knn_vote::thread_sorted_labels_we1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        sorted_labels_we1 = grp_sort_knn_fu_221_sorted_labels_V_we1.read();
    } else {
        sorted_labels_we1 = ap_const_logic_0;
    }
}

void knn_vote::thread_tmp_1_fu_510_p4() {
    tmp_1_fu_510_p4 = p_022_0_reg_199.read().range(2-1, 0);
}

void knn_vote::thread_trunc_ln171_fu_288_p1() {
    trunc_ln171_fu_288_p1 = j_0_in_reg_190.read().range(2-1, 0);
}

void knn_vote::thread_zext_ln169_fu_267_p1() {
    zext_ln169_fu_267_p1 = esl_zext<32,2>(i3_0_reg_133.read());
}

void knn_vote::thread_zext_ln172_fu_283_p1() {
    zext_ln172_fu_283_p1 = esl_zext<64,2>(i3_0_reg_133.read());
}

void knn_vote::thread_zext_ln544_fu_546_p1() {
    zext_ln544_fu_546_p1 = esl_zext<64,4>(p_022_0_reg_199.read());
}

void knn_vote::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(grp_sort_knn_fu_221_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln164_fu_240_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln169_fu_271_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(icmp_ln171_fu_298_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln182_fu_486_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<9>) ("XXXXXXXXX");
            break;
    }
}

}

