// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _sort_knn_HH_
#define _sort_knn_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "dut_mux_305_6_1_1.h"

namespace ap_rtl {

struct sort_knn : public sc_module {
    // Port declarations 56
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<6> > knn_set_0_0_V_read;
    sc_in< sc_lv<6> > knn_set_0_1_V_read;
    sc_in< sc_lv<6> > knn_set_0_2_V_read;
    sc_in< sc_lv<6> > knn_set_1_0_V_read;
    sc_in< sc_lv<6> > knn_set_1_1_V_read;
    sc_in< sc_lv<6> > knn_set_1_2_V_read;
    sc_in< sc_lv<6> > knn_set_2_0_V_read;
    sc_in< sc_lv<6> > knn_set_2_1_V_read;
    sc_in< sc_lv<6> > knn_set_2_2_V_read;
    sc_in< sc_lv<6> > knn_set_3_0_V_read;
    sc_in< sc_lv<6> > knn_set_3_1_V_read;
    sc_in< sc_lv<6> > knn_set_3_2_V_read;
    sc_in< sc_lv<6> > knn_set_4_0_V_read;
    sc_in< sc_lv<6> > knn_set_4_1_V_read;
    sc_in< sc_lv<6> > knn_set_4_2_V_read;
    sc_in< sc_lv<6> > knn_set_5_0_V_read;
    sc_in< sc_lv<6> > knn_set_5_1_V_read;
    sc_in< sc_lv<6> > knn_set_5_2_V_read;
    sc_in< sc_lv<6> > knn_set_6_0_V_read;
    sc_in< sc_lv<6> > knn_set_6_1_V_read;
    sc_in< sc_lv<6> > knn_set_6_2_V_read;
    sc_in< sc_lv<6> > knn_set_7_0_V_read;
    sc_in< sc_lv<6> > knn_set_7_1_V_read;
    sc_in< sc_lv<6> > knn_set_7_2_V_read;
    sc_in< sc_lv<6> > knn_set_8_0_V_read;
    sc_in< sc_lv<6> > knn_set_8_1_V_read;
    sc_in< sc_lv<6> > knn_set_8_2_V_read;
    sc_in< sc_lv<6> > knn_set_9_0_V_read;
    sc_in< sc_lv<6> > knn_set_9_1_V_read;
    sc_in< sc_lv<6> > knn_set_9_2_V_read;
    sc_out< sc_lv<5> > sorted_distances_V_address0;
    sc_out< sc_logic > sorted_distances_V_ce0;
    sc_out< sc_logic > sorted_distances_V_we0;
    sc_out< sc_lv<6> > sorted_distances_V_d0;
    sc_in< sc_lv<6> > sorted_distances_V_q0;
    sc_out< sc_lv<5> > sorted_distances_V_address1;
    sc_out< sc_logic > sorted_distances_V_ce1;
    sc_out< sc_logic > sorted_distances_V_we1;
    sc_out< sc_lv<6> > sorted_distances_V_d1;
    sc_in< sc_lv<6> > sorted_distances_V_q1;
    sc_out< sc_lv<5> > sorted_labels_V_address0;
    sc_out< sc_logic > sorted_labels_V_ce0;
    sc_out< sc_logic > sorted_labels_V_we0;
    sc_out< sc_lv<4> > sorted_labels_V_d0;
    sc_in< sc_lv<4> > sorted_labels_V_q0;
    sc_out< sc_lv<5> > sorted_labels_V_address1;
    sc_out< sc_logic > sorted_labels_V_ce1;
    sc_out< sc_logic > sorted_labels_V_we1;
    sc_out< sc_lv<4> > sorted_labels_V_d1;
    sc_in< sc_lv<4> > sorted_labels_V_q1;


    // Module declarations
    sort_knn(sc_module_name name);
    SC_HAS_PROCESS(sort_knn);

    ~sort_knn();

    sc_trace_file* mVcdFile;

    dut_mux_305_6_1_1<1,1,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,5,6>* dut_mux_305_6_1_1_U1;
    sc_signal< sc_lv<7> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<4> > i_V_fu_420_p2;
    sc_signal< sc_lv<4> > i_V_reg_744;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<37> > lhs_V_fu_452_p1;
    sc_signal< sc_lv<37> > lhs_V_reg_749;
    sc_signal< sc_lv<1> > icmp_ln887_fu_414_p2;
    sc_signal< sc_lv<5> > sub_ln321_fu_472_p2;
    sc_signal< sc_lv<5> > sub_ln321_reg_754;
    sc_signal< sc_lv<2> > j_fu_484_p2;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<5> > i_fu_557_p2;
    sc_signal< sc_lv<5> > i_reg_770;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<5> > j_1_fu_569_p2;
    sc_signal< sc_lv<5> > j_1_reg_778;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<64> > zext_ln131_fu_575_p1;
    sc_signal< sc_lv<64> > zext_ln131_reg_783;
    sc_signal< sc_lv<1> > icmp_ln130_fu_563_p2;
    sc_signal< sc_lv<64> > zext_ln131_1_fu_580_p1;
    sc_signal< sc_lv<64> > zext_ln131_1_reg_788;
    sc_signal< sc_lv<5> > sorted_distances_V_a_1_reg_793;
    sc_signal< sc_lv<5> > sorted_distances_V_a_2_reg_798;
    sc_signal< sc_lv<1> > icmp_ln895_fu_585_p2;
    sc_signal< sc_lv<1> > icmp_ln895_reg_803;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<5> > sorted_labels_V_addr_1_reg_807;
    sc_signal< sc_lv<5> > sorted_labels_V_addr_2_reg_813;
    sc_signal< sc_lv<4> > t_V_reg_368;
    sc_signal< sc_lv<1> > icmp_ln121_fu_478_p2;
    sc_signal< sc_lv<2> > i_op_assign_reg_381;
    sc_signal< sc_lv<5> > i1_0_reg_392;
    sc_signal< sc_lv<5> > j2_0_reg_403;
    sc_signal< sc_lv<1> > icmp_ln129_fu_551_p2;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<64> > zext_ln544_fu_499_p1;
    sc_signal< sc_lv<6> > tmp_2_fu_514_p32;
    sc_signal< sc_lv<6> > shl_ln_fu_430_p3;
    sc_signal< sc_lv<7> > zext_ln1352_1_fu_438_p1;
    sc_signal< sc_lv<7> > zext_ln1352_fu_426_p1;
    sc_signal< sc_lv<7> > ret_V_fu_442_p2;
    sc_signal< sc_lv<36> > sext_ln1352_fu_448_p1;
    sc_signal< sc_lv<3> > trunc_ln321_fu_460_p1;
    sc_signal< sc_lv<5> > shl_ln1_fu_464_p3;
    sc_signal< sc_lv<5> > zext_ln321_fu_456_p1;
    sc_signal< sc_lv<37> > rhs_V_fu_490_p1;
    sc_signal< sc_lv<37> > ret_V_1_fu_494_p2;
    sc_signal< sc_lv<5> > zext_ln321_1_fu_505_p1;
    sc_signal< sc_lv<5> > tmp_2_fu_514_p31;
    sc_signal< sc_lv<7> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<7> ap_ST_fsm_state1;
    static const sc_lv<7> ap_ST_fsm_state2;
    static const sc_lv<7> ap_ST_fsm_state3;
    static const sc_lv<7> ap_ST_fsm_state4;
    static const sc_lv<7> ap_ST_fsm_state5;
    static const sc_lv<7> ap_ST_fsm_state6;
    static const sc_lv<7> ap_ST_fsm_state7;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<4> ap_const_lv4_A;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<5> ap_const_lv5_1E;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<5> ap_const_lv5_1D;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_i_V_fu_420_p2();
    void thread_i_fu_557_p2();
    void thread_icmp_ln121_fu_478_p2();
    void thread_icmp_ln129_fu_551_p2();
    void thread_icmp_ln130_fu_563_p2();
    void thread_icmp_ln887_fu_414_p2();
    void thread_icmp_ln895_fu_585_p2();
    void thread_j_1_fu_569_p2();
    void thread_j_fu_484_p2();
    void thread_lhs_V_fu_452_p1();
    void thread_ret_V_1_fu_494_p2();
    void thread_ret_V_fu_442_p2();
    void thread_rhs_V_fu_490_p1();
    void thread_sext_ln1352_fu_448_p1();
    void thread_shl_ln1_fu_464_p3();
    void thread_shl_ln_fu_430_p3();
    void thread_sorted_distances_V_address0();
    void thread_sorted_distances_V_address1();
    void thread_sorted_distances_V_ce0();
    void thread_sorted_distances_V_ce1();
    void thread_sorted_distances_V_d0();
    void thread_sorted_distances_V_d1();
    void thread_sorted_distances_V_we0();
    void thread_sorted_distances_V_we1();
    void thread_sorted_labels_V_address0();
    void thread_sorted_labels_V_address1();
    void thread_sorted_labels_V_ce0();
    void thread_sorted_labels_V_ce1();
    void thread_sorted_labels_V_d0();
    void thread_sorted_labels_V_d1();
    void thread_sorted_labels_V_we0();
    void thread_sorted_labels_V_we1();
    void thread_sub_ln321_fu_472_p2();
    void thread_tmp_2_fu_514_p31();
    void thread_trunc_ln321_fu_460_p1();
    void thread_zext_ln131_1_fu_580_p1();
    void thread_zext_ln131_fu_575_p1();
    void thread_zext_ln1352_1_fu_438_p1();
    void thread_zext_ln1352_fu_426_p1();
    void thread_zext_ln321_1_fu_505_p1();
    void thread_zext_ln321_fu_456_p1();
    void thread_zext_ln544_fu_499_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
